### ISSUE TITLE
clustering function for features

### ISSUE THREAD

**Issue by hspitzer** [scverse/squidpy#246]
When writing tutorials, I find myself defining the same clustering function in several notebooks. 
```
def cluster_features(features: pd.DataFrame, like=None):
    """Calculate leiden clustering of features.

    Specify filter of features using `like`.
    """
    # filter features
    if like is not None:
        features = features.filter(like=like)
    # create temporary adata to calculate the clustering
    adata = ad.AnnData(features)
    # adata.var_names_make_unique()
    # important - feature values are not scaled, so need to scale them before PCA
    sc.pp.scale(adata)
    # calculate leiden clustering
    sc.pp.pca(adata, n_comps=min(10, features.shape[1] - 1))
    sc.pp.neighbors(adata)
    sc.tl.leiden(adata)

    return adata.obs["leiden"]
```

This essentially does scaling+PCA+neighbors+leiden on a set of features. 
I was wondering if we should include this in squidpy as a convenience function (maybe made a bit more general)? Or should we rather leave these sort of functions outside of squidpy? Is there a solution that I can avoid defining the same function in several notebooks? @giovp

**Comment by giovp** [comment]
it would be cool to have a multiplex partition based on layers/obsm
see this https://github.com/theislab/scanpy/issues/1818
