### ISSUE TITLE
Project Spatially Barcoded Features into Space (append to AnnData object)

### ISSUE THREAD

**Issue by junyho486** [scverse/squidpy#421]
Hi, thanks for creating squidpy! :)

I would be interested if it is possible to add Observations not included in the current Visium-Run to the AnnData object.
E.G. project manually created Features into the spatial context.

**Comment by giovp** [comment]
still a bit difficult to understand sorry:
- what's a count column? 
- what are the features?
- what's the spatial barcode?
In general, in anndata we have a cell (obs) x gene (var) representations, and than we save 
- obs annotation in `adata.obs` (e.g. your clusters)
- var annotations in `adata.var` (e.g. gene annotations)
- the spatial coordinates, or any obs-wise representation (e.g. PCA etc) in `adata.obsm`. E.g. the spatial coordinates are in `adata.obsm["spatial"]`

can you provide examples (e.g. `dataframe.head()`) of your data that you'd like to cast in anndata? thanks!

**Comment by giovp** [comment]
Hi @junyho486 ,

thanks for the clarification. It sounds a really cool application and cross-interoperability of the scanpy ecosystem, cool!
As to your question, you can store the whole information in this table in `adata.obs`, making sure that the indexes match with the `Visium Barcode` series (assuming you already have a Visium AnnData ).

You could then easily use any of the scanpy/squidpy and I believe scirpy functions as well. E.g. if you want to visualize TCR counts you'd have to do 

```python
sc.pl.spatial(adata, color = "Count")
```
does that help?
