### ISSUE TITLE
Provide AnnData viewer as Napari plugin

### ISSUE THREAD

**Issue by aeisenbarth** [scverse/squidpy#429]
## Feature

The `Interactive` viewer is currently implemented as an **application** (wrapping and using Napari as a view component), which can, as far as I could see, only be launched from a Jupyter notebook or Python code and only by providing all required arguments. It would be useful to have the AnnData viewing capability also available as a Napari **plugin**.

## Motivation

- Napari plugins can live side by side, and the user has access to **tools from many different plugins** and can combine them. Sure, one could install plugins from pypi into the notebook's Python environment and when starting `Interactive`, Napari will detect and load them. But:
- The user has more **flexibility** working with **several datasets** (e.g. adata + non-adata layers), if it is not required to launch a new `Interactive` instance every time. Also state of plugins and other data (layers) would be preserved if the user chooses to work in a single instance.
- When deploying tools for users, it is nicer to build workflows around selected plugins and with Napari as the **top-level application**, instead of having several tools want to be at the top-level.
- The community extends the **ecosystem** on [Napari Hub](https://www.napari-hub.org/) primarily with plugins. At the moment, users cannot yet find AnnData support there and thus a very useful tool is missing!

I see there might have been reasons to implement the initial version as it is, also due to various limitations of Napari's plugin hooks (isolation of IO vs. GUI hooks). But these could be overcome by for example combining both docks (one has only a single colorbar) into a single dock and by storing `adata` as a reference in the image layer's metadata.

## Pitch

Release an official spatial AnnData viewer as a plugin for Napari.

## Alternatives

As it is not too hard to build a plugin with the [cookiecutter](https://github.com/napari/cookiecutter-napari-plugin) template, someone else might do it. But I think the right place for it would be above all the official AnnData/Squidpy project.

**Comment by giovp** [comment]
Hi @aeisenbarth , thanks a lot for the interest and the suggestion. Indeed this is very important and beneficial for downstream use cases. We had something in mind very similar to what you described in this issue and applied for a CZI napari plugin funding last summer. We are very happy to announce that we were awarded the grant and therefore will start working on it very soon! more info here: https://chanzuckerberg.com/science/programs-resources/imaging/napari/interactive-visualization-of-spatial-omics-data/

I'll report back here when as soon as we kickstart the plugin development.

**Comment by giovp** [comment]
it's live, you can check `scverse/napari-spatialdata`
