### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by ivirshup** [scverse/squidpy#469]
It would be great if this package could be distributed via condo-forge as well as pip. I'd like for `mamba install squidpy` to work so the package doesn't have to be special cased when making a conda env.

**Comment by giovp** [comment]
doable to be considered for next release

**Comment by michalk8** [comment]
2 questions:
- do we wanna go for `conda-forge` or `bioconda`? no strong preference
- shall we package `napari/pyqt` as well or create a subpackage?

**Comment by ivirshup** [comment]
I'd go for `conda-forge`. We've got scanpy, anndata, and scvi-tools in there, so there more knowledge of the CI system in scverse.

Also if you go bioconda, but all your dependencies use conda-forge now you're pulling from more channels which can make dependency resolution slow or even fail.

**Comment by giovp** [comment]
> shall we package napari/pyqt as well or create a subpackage?

let's create a subpackage, talk on Fri about this

**Comment by giovp** [comment]
I believe this can be close as we have it in conda now
