### ISSUE TITLE
Does ligrec function take factor in cell-cell proximity? 

### ISSUE THREAD

**Issue by rgranit** [scverse/squidpy#470]
I've looked at the [docs](https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_seqfish.html), but could not figure out if the ligrec takes into consideration the cell-cell proximity, or does it rely only on expression?

Thanks!

**Comment by giovp** [comment]
hi @rgranit ,
it does not. However, you can use the results to filter out e.g. LR interactions based on neighboring cell types.
HTH 
GIovanni
