### ISSUE TITLE
Plotting different conditions together using pl.ligrec

### ISSUE THREAD

**Issue by Tonyspuri** [scverse/squidpy#491]
Hi all,

Thanks a lot for developing the great package. I've been using it for ligand receptor analysis and more recently with accumulation of different datasets, I would like to plot differences between two or more different conditions. I can generate dot plots for each library individually but didn't manage to plot multiple timepoints in a single plot. Is it something doable with pl.logrec plotting? 

Cheers!
...

**Comment by giovp** [comment]
thanks for interest in Squidpy @Tonyspuri , can you elaborate more what are you trying to do? I don't think is in scope to run lig_rec across different slides, so I'd maybe compute it for each slide separately and then find a way to aggregate them?

**Comment by Tonyspuri** [comment]
I have scRNA-seq datasets from different conditions e.g. WT vs mutant and basically would like to plot lig_rec dotplots on the same plot next to each other. Right now I generate separate dictionaries for the individual libraries and I can plot them separately but we can't plot different conditions together.  If I understand correctly I have to find a way to merge different dictionaries and plot them afterwards?

**Comment by giovp** [comment]
hi @Tonyspuri indeed you'd have to tweak `sc.DotPlot` , this is not a priority for now but happy to support if you want to submit a PR. Othewise, I would close this.
