### ISSUE TITLE
cellphonedb ligrec plot

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/squidpy#502]
Hi,
Does sq.pl.ligrec support plots similar to cellphoneDB ?
Because when there are many clusters, the interaction plot generated will be very large and hard to save and to see. In this case, the following summary plots are very useful. Different shape/size/color represents the terms among clusters, and the interacting molecules are not necessary to be plotted. Only the summary are needed.
![cellphoneDB](https://user-images.githubusercontent.com/29703450/161410531-823cb733-1336-4f3e-8029-494e9b6c915a.jpeg)

**Comment by giovp** [comment]
hi @wangjiawen2013 , you are talking about the heatmap on the right? If yes, unfortunately we don't have such visualization and it is no planned. However, it seems doable to do by aggregating results from the function, as it is outlined in this tutorial https://squidpy.readthedocs.io/en/latest/auto_examples/graph/compute_ligrec.html (you'd have to aggregate the "means" and "pvalues" tables, accordingly to whether you are interested in counting interactions by significance)

**Comment by giovp** [comment]
it's actually really doable, keeping it open for reminder, maybe in the future

**Comment by michalk8** [comment]
> it's actually really doable, keeping it open for reminder, maybe in the future

Agreed, we have the private `_heatmap` implementation that we could use for this. Will look at this later.

**Comment by wangjiawen2013** [comment]
CellPhoneDB has been updated to v3, which incorporate spatial information. Does sq.gr.ligrec adopt this version ?

**Comment by michalk8** [comment]
> CellPhoneDB has been updated to v3, which incorporate spatial information. Does sq.gr.ligrec adopt this version ?

Unfortunately, I don't know. I'd ask here directly, as we're using `omnipath`: https://github.com/saezlab/pypath/issues

**Comment by giovp** [comment]
> CellPhoneDB has been updated to v3, which incorporate spatial information. Does sq.gr.ligrec adopt this version ?

sorry am also not familiar with it, in which way does it incorporate spatial information?

**Comment by wangjiawen2013** [comment]
please refer to cellphoneDB v3 paper: https://www.nature.com/articles/s41588-021-00972-2
"Mapping the temporal and spatial dynamics of the human endometrium in vivo and in vitro"

**Comment by wangjiawen2013** [comment]
Hi,
which kind of data does ligrec need ? raw counts or lognormailized counts ?

**Comment by giovp** [comment]
hi @wangjiawen2013 ,

I think the way they incorporate spatial information is by simply subsetting the ligrec output with cell types that are known to co-occurr in visium spots, it's more an analysis step rather than a method step. I'd close this for now.
