### ISSUE TITLE
get_axis() for pl.ligrec 

### ISSUE THREAD

**Issue by Tonyspuri** [scverse/squidpy#532]
## Description

...
Thanks everyone for developing Squidpy. I just had a small request/question regarding plotting ligrec. 
After plotting ligrec dotplots, I usually want to see whether ligand or receptor expression is changing in different conditions for given cell types. For that I usually manually pick genes based on the plots. Is there a way to export the list of receptors or ligands from ligrec plot to then plot their expression separately on scanpy object? I thought something like get_axis() (similar to scanpy dotplot) and splitting receptors and ligands afterwards would be helpful but pl.ligrec doesn't seem to have the option. Is there any other way where I can export receptor and ligand list from the plot? 

Cheers!

**Comment by giovp** [comment]
hi @Tonyspuri , thanks for interesting in Squidpy, this should be doable, I'll take a look in the coming weeks

**Comment by giovp** [comment]
hi @Tonyspuri , clearly didn't have time and won't have time to work on this in the future. Let me know if you are interested in contributing otherwise I'd close this due to inactivity
