### ISSUE TITLE
H&E Image Features

### ISSUE THREAD

**Issue by DaisyCuttie** [scverse/squidpy#541]
Hi, I am currently learning Squidpy calculate image features. I am wondering what is the interpretation of the pattern? I could not figure out why there are circles of low-mean image features(how to interpret the location of the circles).  Also, channel 0,1 and 2 do not seem be too different on the tissue sample I am working on. 
<img width="1060" alt="Screen Shot 2022-05-04 at 10 01 32 PM" src="https://user-images.githubusercontent.com/23642391/166865957-42ed6157-147e-435c-a58c-8208a333d3bd.png">
For this, I used the tutorial on this site [https://squidpy.readthedocs.io/en/stable/auto_examples/image/compute_features.html#sphx-glr-auto-examples-image-compute-features-py](url)
I tried custom_features as well, but did not get any difference.
<img width="948" alt="Screen Shot 2022-05-04 at 10 03 04 PM" src="https://user-images.githubusercontent.com/23642391/166866057-5960274f-bc16-477e-90ca-d4918b4edc08.png">

I would be grateful if you can provide some insights of the results I am getting!

**Comment by Charlottehero** [comment]
Thank you for the reply! 
I first loaded in the tif image file our team has using image container function,
`img = sq.im.ImageContainer("path/to/image.tif", scale = scale)`
and I used the default image feature calculation function in the tutorial.
`feature_name = "features_summary"
sq.im.calculate_image_features(
        adata,
        img,
        features="summary",
        key_added=feature_name,
        n_jobs=4,
        scale=scale,
    )`
Btw, we are also not sure why the intensity value range is very narrow across the whole tissue. Is there anything wrong with our code?

**Comment by giovp** [comment]
apologies for late reply, I must say it's difficult to debug with this info. Are you sure that image features calculcation is computed on the same (or a scaled version) of the tissue image that you use for plotting? 

Re intesnity ranges, it looks like the iamge is in 8but instead of 16bit so it's not necessarily low (thje max is 255)

**Comment by giovp** [comment]
@DaisyCuttie I'll close this issue due to inactivity, let me know if the problem persist and feel free to reopen the issue!
