### ISSUE TITLE
spatial neighbors and datasets integration

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/squidpy#543]
Hi,
I don't quite understand about the "library_key" parameter in sq.gr.spatial_neighbors. I have integrated several datasets in an anndata object, the datasets are from different 10xvisium samples. In this case, how the neighbors are computed ? The spatial coordinates of the spots  will be the same among different samples, so I wanna the ways that squidpy process this kind of object. In fact, all the downstream analysis, such moranI, ripleyL, co occurrence are related to this kind of problems and this is a question about spatial transcriptome data integration.

**Comment by giovp** [comment]
hey @wangjiawen2013 `library_key` is the key in `adata.obs` that soters the various `library_ids` I think we have tutorials for now in multiple places around the docs, will close but please feel free to reopen
