### ISSUE TITLE
Squidpy cannot fit matplotlib 3.5.2

### ISSUE THREAD

**Issue by HelloWorldLTY** [scverse/squidpy#545]
If I use matplotlib 3.5.2, I will receive this bug:
[Matplotlib AttributeError: module 'matplotlib.cbook' has no attribute '_define_aliases'](https://stackoverflow.com/questions/53421905/matplotlib-attributeerror-module-matplotlib-cbook-has-no-attribute-define-a)
If I use 3.5.0, the package can work normally.

How to address this problem? Thanks a lot.

**Comment by michalk8** [comment]
Hi @HelloWorldLTY , could you please provide a small code snippet to reproduce?

**Comment by giovp** [comment]
hi @HelloWorldLTY I will close this issue due to inactivity, feel free to reopen
