### ISSUE TITLE
What does the units of 'nhood_enrichment' plot represent?

### ISSUE THREAD

**Issue by rgranit** [scverse/squidpy#555]
Hi All,

When using the `sq.pl.nhood_enrichment` function we obtain a heatmap with certain scale - what do the values represent?  can one obtain statistical significance of the results?

Thanks!

**Comment by giovp** [comment]
hi @rgranit I would check the paper https://www.nature.com/articles/s41592-021-01358-2 it's basically a test statistics based on permutations. HTH, will close but please feel free to reopen if needed. Also apologies for super late reply.
