### ISSUE TITLE
problems with sq.gr.ligrec

### ISSUE THREAD

**Issue by livyring** [scverse/squidpy#563]
Hi! I am trying to compute receptor ligand interactions with this function. I use my adata object (preprocessed Visium 10X data - used scanpy for preprocessing) which looks like this: 

```python
AnnData object with n_obs × n_vars = 1851 × 14433
    obs: 'in_tissue', 'array_row', 'array_col', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_Ribo', 'pct_counts_Ribo', 'total_counts_Hb', 'pct_counts_Hb', 'percent_mt2', 'n_counts', 'clusters'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'Ribo', 'Hb', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'hvg', 'leiden', 'log1p', 'neighbors', 'pca', 'spatial', 'umap', 'rank_genes_groups', 'spatial_neighbors'
    obsm: 'X_pca', 'X_umap', 'spatial'
    varm: 'PCs'
    obsp: 'connectivities', 'distances', 'spatial_connectivities', 'spatial_distances'

and run the following code:

res = sq.gr.ligrec(
    adata,
    use_raw = False,
    n_perms=10,
    cluster_key="clusters",
    copy = True,
    source_groups = "5",
    target_groups = ["4", "6"],
    transmitter_params={"categories": "ligand"},
    receiver_params={"categories": "receptor"},
    interactions_params={'resources': 'CellPhoneDB'},
)

res["means"].head()
```

My clusters are not annotated yet, they are just numbered 0-7 from after the clustering that was done in the preprocessing tutorial. 

**I get this error:** 
An attempt has been made to start a new process before the
    current process has finished its bootstrapping phase.
 
    This probably means that you are not using fork to start your
    child processes and you have forgotten to use the proper idiom
    in the main module:
 
        if __name__ == '__main__':
            freeze_support()
            ...
 
    The "freeze_support()" line can be omitted if the program
    is not going to be frozen to produce an executable.

EOFError

I ran the example code for this process with the example H&E dataset, and it worked. So it makes me think that something is wrong with my Anndata object or not being passed correctly through the function. 

Thanks your your help!!!!

...

**Comment by livyring** [comment]
Hi! I am on a Mac. I have tried changing it to multiprocessing by doing:

#receptor ligand interactions
res = sq.gr.ligrec(
    adata,
    use_raw = False,
    n_perms=10,
    cluster_key="clusters",
    copy = True,
    source_groups = "5",
    target_groups = ["4", "6"],
    transmitter_params={"categories": "ligand"},
    receiver_params={"categories": "receptor"},
    interactions_params={'resources': 'CellPhoneDB'},
    backend = "multiprocessing"
)

res["means"].head()

Unfortunately that still does not work

**Comment by livyring** [comment]
I resolved this by manually setting my backend = loky. Unsure why it was not set this as default

**Comment by giovp** [comment]
you just imported freeze_support and it worked?

**Comment by livyring** [comment]
Yes

**Comment by michalk8** [comment]
Closing this, please re-open if needed.
