### ISSUE TITLE
MNN correction on spatial datasets

### ISSUE THREAD

**Issue by sophieRAIBAUD** [scverse/squidpy#570]
## Description

...hello
I am struggling with 2 spatial transcriptomics data to compare, but the 2 tissues were spoted perpendicular to each other
I dont know how to pivot the whole anndata (with image + transcripomic data)
any idea ?
Many thanks for this wonderfull package !!!

![image](https://user-images.githubusercontent.com/17746001/174264476-3477aa9c-e173-429f-a382-8f59ce6ef282.png)

**Comment by giovp** [comment]
hi @sophieRAIBAUD thanks for the interest, what do you mean "pivot" ?

**Comment by sophieRAIBAUD** [comment]
hello
I mean 90° turn in order to see the pictures (and the data) in the same orientation 
Many thanks !!!

**Comment by giovp** [comment]
maybe scipy can help https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.rotate.html ?

**Comment by sophieRAIBAUD** [comment]
OK thanks !
ill try it for the image but I also will need  to rotate the spatial data

**Comment by sophieRAIBAUD** [comment]
hello Giovanni,
do you think I need to turn the spatial transcriptomic data in order to perform batch correction with MNN on the 2 data than are not spatially aligned ?
Many thanks !
Sophie

**Comment by giovp** [comment]
you don't need to do so, only thing is to rotate the spatial coordinates in `adata.obsm["spatial"]` and the image.

**Comment by giovp** [comment]
@sophieRAIBAUD I believe you don't need to rotate the image for the MNN. I'd be curious to see whether the image and coordiantes before rotation are nonetheless aligned?

**Comment by sophieRAIBAUD** [comment]
Hello Giovanni,
I have performed MNN on my 2 samples following this tutorial:
https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/scanpy/scanpy_03_integration.html
on the PCA, tsne, and umap graphes, it look pretty cool:
![image](https://user-images.githubusercontent.com/17746001/181772730-9d9775ca-2866-458c-b6e9-030cdb2b4c19.png)
![image](https://user-images.githubusercontent.com/17746001/181772844-fc511308-c98f-4973-811e-dd95f1449c8a.png)

but now I would like to perform a louvain clustering on corrected data
but I lost the image in the cdata:
![image](https://user-images.githubusercontent.com/17746001/181774706-4ed98ce2-3236-464b-b898-abb75ae6aedf.png)

I am not sure I am doing the right thing
Many thanks for your help !
Sophie

**Comment by sophieRAIBAUD** [comment]
I found the solution with this notebook
https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/scanpy/scanpy_07_spatial.html
but I had to get back the image data:
corrected.uns['spatial'] = adata_raw.uns['spatial']
it works !

**Comment by sophieRAIBAUD** [comment]
> @sophieRAIBAUD I believe you don't need to rotate the image for the MNN. I'd be curious to see whether the image and coordiantes before rotation are nonetheless aligned?

@giovp next, I'll do it with other data that are not aligned at all
thanks
