### ISSUE TITLE
codex data

### ISSUE THREAD

**Issue by sophieRAIBAUD** [scverse/squidpy#576]
hello again,
do you plan to integrate CODEX data in squidpy package ?
Many thanks
Sophie
...

**Comment by sophieRAIBAUD** [comment]
hello
just want to analysis these kind of data with squidpy (https://www.akoyabio.com/)
which functions work on codex data (I believe its .mav format)
Thanks !!

**Comment by wangjiawen2013** [comment]
The same question !

**Comment by wangjiawen2013** [comment]
Maybe the following link will help !
https://pysodb.readthedocs.io/en/latest/squidpy/pysodb_squidpy_CODEX.html
