### ISSUE TITLE
connection to omnipath using an Amazon Web Services 

### ISSUE THREAD

**Issue by sophieRAIBAUD** [scverse/squidpy#577]
## Description

Dear all
again many thanks for your help on spatial transcriptomic data ....

I have some trouble using **squidpy.gr.ligrec** : error message: Failed to establish a new connection: [Errno 110] Connection timed out'
But I can connect to omnipath using : 
wget https://omnipathdb.org/ **_--no-check-certificate_**  
instead of: 
 **_wget https://omnipathdb.org/_**
is there a way to add the option _**no-check-certificate**_ in the squidpy.gr.ligrec function ?
I have tried to releave the security using os.environ["PYTHONHTTPSVERIFY"]="0" but it does not work
Many thanks 
Sophie

...

**Comment by michalk8** [comment]
Hi @sophieRAIBAUD , this is more of an `omnipath` issue, could you please close this and open it there: https://github.com/saezlab/omnipath?

**Comment by sophieRAIBAUD** [comment]
see https://github.com/saezlab/omnipath/issues/25
