### ISSUE TITLE
interface with NAPARI

### ISSUE THREAD

**Issue by sophieRAIBAUD** [scverse/squidpy#578]
## Description

hello again :)
I am trying to add a point layer to napari in interactive mode. I follow these indications to add cells positions that I got with tangram: https://forum.image.sc/t/napari-plugin-to-display-csv-as-image/37399/3 )
when I type :

     data = sq.datasets.visium_hne_adata()
    img = sq.datasets.visium_hne_image()
    viewer = img.interactive(adata)

the viewer does not accept the .add_points method
viewer.add_points give this error message:
**'Interactive' object has no attribute 'add_points'**

Could you help me with that ?

The other solution would be :
viewer = napari.Viewer();
points_layer = viewer.add_points(
    data)
but I dont know how to add all my squidpy results (clusters, genes, ...)
Many many thanks
sophie
...

**Comment by sophieRAIBAUD** [comment]
the first example is working properly
thanks !

_import napari
import squidpy as sq

adata = sq.datasets.visium_hne_adata()
img1 = adata.uns["spatial"]["V1_Adult_Mouse_Brain"]["images"]["hires"].copy()

viewer = napari.Viewer()
viewer.add_image(
    img1,
    rgb=True,
    name="image1",
    metadata={"adata": adata, "library_id": "V1_Adult_Mouse_Brain"},
)_

**Comment by sophieRAIBAUD** [comment]
for the raster_points_regions I am not really sure what is the fov parameter in adata.obs ....

adata1 = adata[adata.obs.fov == "1"].copy()

**Comment by giovp** [comment]
hi @sophieRAIBAUD , the fov is the single slide of the mibitof dataset. It's just an example to extract a single image (and related annotation) from anndata).

does it help?

**Comment by sophieRAIBAUD** [comment]
@giovp , OK thanks 
I am very happy with the spatial transcriptomic data, except minor comments
can I continue to comment on this channel ?

**Comment by giovp** [comment]
hi @sophieRAIBAUD , for sure! I'd say github is more for bug report and feature requests, whereas discourse is more for usage discussion

**Comment by giovp** [comment]
I'll close this, feel free to reopen if not addressed
