### ISSUE TITLE
Does squidpy.gr.spatial_neighbors evaluate 3D coordinates?

### ISSUE THREAD

**Issue by schienstockd** [scverse/squidpy#581]
Hello,

I have 3D coordinates in `obsm['spatial']`. Does `squidpy.gr.spatial_neighbors` support this? The function seems to be running on my dataset but I am not sure about the output.

Thanks!
...

**Comment by michalk8** [comment]
Hi @schienstockd ,  sorry for the late reply. I quickly checked the code, as far as I could tell, yes, it should work on `3D` (or even `ND`), see [here](https://github.com/scverse/squidpy/blob/main/squidpy/gr/_build.py#L267) or [here](https://github.com/scverse/squidpy/blob/main/squidpy/gr/_build.py#L282-L283), the `coords` should be directly taken from `adata.obsm`.
