### ISSUE TITLE
Co-occurrence gives 'nan' if n_splits>1 in large dataset  

### ISSUE THREAD

**Issue by nadavyayon** [scverse/squidpy#582]
## Description

Hi Squidpy team, great package!
I found un issue with the sq.gr.co_occurrence function returning 'nan's when n_splits>1
On a large dataset with 30K cells this automatically set n_splits to 14 and gave an error.  switching to n_splits=1 fixed it. 
Then to see what's wrong I tried the tutorial - great docs! 

### load the pre-processed dataset
adata = sq.datasets.imc()
sq.gr.co_occurrence(adata, cluster_key="cell type",n_splits=1) 
adata.uns['cell type_co_occurrence']- > fine!
sq.gr.co_occurrence(adata, cluster_key="cell type",n_splits=2) 
adata.uns['cell type_co_occurrence']- > fine!
sq.gr.co_occurrence(adata, cluster_key="cell type",n_splits=3)
adata.uns['cell type_co_occurrence'] - > some nans!
sq.gr.co_occurrence(adata, cluster_key="cell type",n_splits=4) 
adata.uns['cell type_co_occurrence']- > more nans!
...
sq.gr.co_occurrence(adata, cluster_key="cell type",n_splits=7) 
adata.uns['cell type_co_occurrence']- > all nans!

squidpy version - > 1.1.2

Many thanks!! 

Nadav

**Comment by giovp** [comment]
hi @nadavyayon , indeed , this is because we split the dataset and this doesn't play well with the cluster annotation. I think this function would require a refactoring, I'll keep this issue open until I have time to address it

**Comment by nadavyayon** [comment]
Cheers! Yeah I can imagine it's not trivial,  fortunately it handles large datasets with n_splits=1. Perhaps would be a good idea to set the default to 1 regardless of data size?

**Comment by giovp** [comment]
> Cheers! Yeah I can imagine it's not trivial, fortunately it handles large datasets with n_splits=1. Perhaps would be a good idea to set the default to 1 regardless of data size?

yeah, not sure what you mean by "large" but e.g. it can't handle 100k observations, unless splitted. The reason to default to split according to dataset size is that, otherwise, it would crash with OOM error if dataset too large.  We could also just raise a warning though, but again best would be to refactor iwth kdtree + max distance.

**Comment by nadavyayon** [comment]
Yeah so I used this on 60K without any issues. didn't try on 100k. However I can see many situations where there could be more than 100K cell in a section

**Comment by yubin-ai** [comment]
I can confirm the error is still here.
