### ISSUE TITLE
Best practise for sample integration

### ISSUE THREAD

**Issue by simonmfr** [scverse/squidpy#588]
Do you have any recommendations about the concatenation of Visium spots from multiple samples into a single anndata object? Is it valid to analyse them together using the single-cell pipeline? Do you recommend to use single-cell-derived batch correction methods?

I am not referring to spatial statistics across samples (discussed before #457 #516 #318 ), but only to the analysis in the latent space, such as done by [Asp et al 2019 Cell](https://pubmed.ncbi.nlm.nih.gov/31835037/).

I saw that this has partly been discussed in #332 but mostly about technical aspects, not best practices.

**Comment by giovp** [comment]
hi @simonmfr 

thank you for the interest in squidpy. For this type of question of best practices, I'd like to point you to https://discourse.scverse.org/ , you can ask the question directly there and I'll answer promptly!

In short, I think single-cell batch correction methods are suitable (ofc up to each of the methods limitations) and I would analyze them together yes.

**Comment by simonmfr** [comment]
Hi @giovp, thanks for your reply, I will have a look!

**Comment by giovp** [comment]
hi @simonmfr , will close this issue due to inactivity, feel free to reopen if the problem persist.
