### ISSUE TITLE
sc.read_visium() and tissue positions

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/squidpy#595]
Hi,
This is an issue originally posted on scanpy github, but I think it more related to squidpy, so I move it here.
https://github.com/scverse/squidpy/issues/599

**Comment by giovp** [comment]
hi @wangjiawen2013 , thank you so much! does the function `read.visium` in squidpy still doesn't work with the new spaceranger? we had a PR from 10x genomics folks that should have fixed that.

**Comment by giovp** [comment]
duplicated in #599
