### ISSUE TITLE
Squidpy doesn't run

### ISSUE THREAD

**Issue by xiaoxiaozhihuishu** [scverse/squidpy#597]
### Hi, I am currently learning Squidpy. When I run Squidpy, however,  it doesn't work. This is my code, and is written following the tutorial.

```
import scanpy as sc
import anndata as ad
import squidpy as sq
from PIL import Image

import numpy as np
import pandas as pd

sc.logging.print_header()
print(f"squidpy=={sq.__version__}")

#img = sq.datasets.visium_hne_image()
#adata = sq.datasets.visium_hne_adata()

source_image = "./visium_hne.tiff"
Image.MAX_IMAGE_PIXELS = None
im = Image.open(source_image)
image = np.array(im)
img = sq.im.ImageContainer(image,library_id = "V1_Adult_Mouse_Brain")

adata = sc.read_h5ad("visium_hne.h5ad")

sc.pl.spatial(adata, color="cluster")

for scale in [1.0, 2.0]:
    feature_name = f"features_summary_scale{scale}"
    sq.im.calculate_image_features(
        adata,
        img.compute(),
        features="summary",
        key_added=feature_name,
        n_jobs=4,
        scale=scale,
    )

adata.obsm["features"] = pd.concat(
    [adata.obsm[f] for f in adata.obsm.keys() if "features_summary" in f], axis="columns"
)

adata.obsm["features"].columns = ad.utils.make_index_unique(adata.obsm["features"].columns)

```

**Comment by xiaoxiaozhihuishu** [comment]
![image](https://user-images.githubusercontent.com/49070206/190083152-0774573c-ca6f-445f-9937-cc0c7f45b9f6.png)

### Process has been always at 0% , no progress

**Comment by giovp** [comment]
hi @xiaoxiaozhihuishu ,

thank you for reporting this issue. Unfortunately, I don't think I'd be able to help much. It looks you are running squidpy on a windows computer, and we do not test squidpy on windows so we can't grant support. The error seems related to a joblib issue (the tool that implements the parallelization), I'd suggest you to try out different parallel backends (threads, loky https://joblib.readthedocs.io/en/latest/parallel.html) and set different n_jobs (-1, 1, 2) . You can see the signature description of the function that I believe is stalling here https://squidpy.readthedocs.io/en/stable/api/squidpy.im.calculate_image_features.html

good luck!

**Comment by xiaoxiaozhihuishu** [comment]
> hi @xiaoxiaozhihuishu ,
> 
> thank you for reporting this issue. Unfortunately, I don't think I'd be able to help much. It looks you are running squidpy on a windows computer, and we do not test squidpy on windows so we can't grant support. The error seems related to a joblib issue (the tool that implements the parallelization), I'd suggest you to try out different parallel backends (threads, loky https://joblib.readthedocs.io/en/latest/parallel.html) and set different n_jobs (-1, 1, 2) . You can see the signature description of the function that I believe is stalling here https://squidpy.readthedocs.io/en/stable/api/squidpy.im.calculate_image_features.html
> 
> good luck!

Thank you for the reply!  Now I run squidpy on Linux，and Squidpy run well. Previously，I really ran squidpy on Windows.

**Comment by giovp** [comment]
great, I'll close this issue then, feel free to reopen if problem persist
