### ISSUE TITLE
ERROR: Unable to fetch palette, reason: 'cell_type_colors'. Using `None`.

### ISSUE THREAD

**Issue by YuanningEric** [scverse/squidpy#598]
When using the `sq.pl.centrality_scores(adata, cluster_key="cell_type")` function, I received this error. Has it been seen before? Did I miss something?

...

**Comment by giovp** [comment]
hi @YuanningEric which error?

**Comment by YuanningEric** [comment]
> ERROR: Unable to fetch palette, reason: 'cell_type_colors'. Using None.

**Comment by giovp** [comment]
hi @YuanningEric 

can you please make a reproducible example and post the full traceback>? It's very difficult to help debug your code with such little information
