### ISSUE TITLE
Closeness centrality above 1

### ISSUE THREAD

**Issue by Hrovatin** [scverse/squidpy#602]
Is it normal that closeness centrality is above 1? I get such a result for some cell types.

I subset adata to single slide and then compute the score as indicated below
```
adata_rep=adata[(adata.obs[groupby]==group).values &
                (adata.obs[replicate_key]==replicate).values,:].copy()
sq.gr.spatial_neighbors(adata=adata_rep,
                        **spatial_neighbors_kwargs)
sq.gr.centrality_scores(adata=adata_rep, cluster_key=cluster_key, 
                        **centrality_scores_kwargs)
```

**Comment by giovp** [comment]
it is, see https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.closeness_centrality.html#networkx.algorithms.centrality.closeness_centrality
