### ISSUE TITLE
Segmentation Fault when Calculating Spatial Autocorrelation

### ISSUE THREAD

**Issue by axelalmet** [scverse/squidpy#611]
## Description

Dear Squidpy Team,

Previously I have used Squidpy's 'gr.spatial_autocorr` function to calculate the Moran's I values for genes to great effect. However, recently, I find that using the function, for however many genes, causes my Python to crash. I find that it happens even when I try to reproduce the Visium H&E [tutorial](https://squidpy.readthedocs.io/en/stable/auto_tutorials/tutorial_visium_hne.html), and it also happens when I try and run the code using either Python 3.8 or Python 3.10. 

Below is the code I ran:

```
import scanpy as sc
import anndata as ad
import squidpy as sq

import numpy as np
import pandas as pd

sc.logging.print_header()
print(f"squidpy=={sq.__version__}")

# load the pre-processed dataset
img = sq.datasets.visium_hne_image()
adata = sq.datasets.visium_hne_adata()

sq.gr.spatial_neighbors(adata)

genes = adata[:, adata.var.highly_variable].var_names.values[:1000]
sq.gr.spatial_autocorr(
    adata,
    mode="moran",
    genes=genes,
    n_perms=100,
    n_jobs=1,
)
```

The versions of all the Python modules I am using are:
```
scanpy==1.9.1 anndata==0.8.0 umap==0.5.3 numpy==1.23.3 scipy==1.9.1 pandas==1.5.0 scikit-learn==1.1.2 statsmodels==0.13.2 python-igraph==0.10.1 pynndescent==0.5.7
squidpy==1.2.2
```
And this is the following error I get:
```
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Segmentation fault: 11
```
The above warning about omp_set_nested has happened in the past but has not been an issue. The segmentation fault is the new occurrence that I do not get. If you have any advice on how to fix this, I would greatly appreciate it. Thank you!

Best wishes,
Axel.

**Comment by giovp** [comment]
I think it's numba, what's the numba version?

**Comment by axelalmet** [comment]
Hi @giovp, this tracks to me, as I think I updated numba recently for a different Python package. My numba version is currently 0.56.2.

**Comment by axelalmet** [comment]
Hi @giovp,

I see, thank you for clarifying! Until it gets fixed in a later version of squidpy, I'm personally fine with reinstalling squidpy in a virtual environment where I pin the numba version to 0.55.0. 

Thanks again for your help!

**Comment by giovp** [comment]
you're welcome and apologies, it's on my todo list.

**Comment by giovp** [comment]
we should really try to get numba (and numpy) up to date for 1.3

**Comment by giovp** [comment]
hi @axelalmet ,

I think this issue is fixed, in main now there is no pin to numba version,. I also encountered sometime the kernel dying but usually refreshing with a new conda env should work. We tested the function with latest numba.
