### ISSUE TITLE
mapping of dots to slides after sc.concat is broken

### ISSUE THREAD

**Issue by stela2502** [scverse/squidpy#613]
## Description

I followed the tutorial https://scanpy-tutorials.readthedocs.io/en/latest/spatial/integration-scanorama.html
and merged 4 datasets using 
```
spatial = sc.concat(
    adata,
    label="library_id",
    uns_merge="unique",
    keys=[
        k
        for d in [
            adata[0].uns["spatial"],
            adata[1].uns["spatial"],
            adata[2].uns["spatial"],
            adata[3].uns["spatial"],
        ]
        for k, v in d.items()
    ],
    index_unique="-",
)
````
with adata obviousely being a list of 4 squidpy objects. 
The image data was also incorrect. Instead of maintaining the images of the respective plot the images were replaced by the first image.
But this might also be incorrectly observed by me. Can not check any more as I have corrected that.
...

## Minimal reproducible example

So I simply hope this is true, too:
Just follow the tutorial and see that the plots look different for

```python

sc.pl.spatial(
   adata_spatial [adata_spatial.obs['library_id'] == adata_spatial.obs['library_id'].unique()[0] ],
    img_key="hires",
    color=['SPINK1'],
    size=1.5,library_id=adata_spatial.obs['library_id'].unique()[0] 
)
```
sc.pl.spatial(
    adata_spatial,
    img_key="hires",
    color=['SPINK1'],
    size=1.5,library_id=adata_spatial.obs['library_id'].unique()[0] 
)
```
The second plots all data even though I only ask for library_id = adata_spatial.obs['library_id'].unique()[0]

```

## Traceback

There is no traceback as it is a logical, no programming error. Of casue only if you agree that only one slide of a merged obejct should be plotted at a time.

## Version

squidpy==1.2.2
scanorama==1.7.2

...

**Comment by stela2502** [comment]
Oh no!
I am sorry I screwed up!
The function I am using to plot is actually
```
sq.pl.spatial_scatter(spatial, color=["SPINK1", "louvain"],library_key="P20065_102")
```
The usage of that leads to totally unexpected results:
I have 4 slides that I merged together following your merge tutorial.
If I use the above function I not only get 8 plots instead of 2 (giving the library_key links to only one slide), 
no I also see all gene expression from all slides overlaying each other.

If I run it like that:
```
sq.pl.spatial_scatter(spatial[spatial.obs['library_id'] == spatial.obs['library_id'].unique()[3] ],
                    color=['SPINK1'],
                    library_key=spatial.obs['library_id'].unique()[3])
```
I at least only see the expression from the last slide, but overplayed over all different 4 slides.

I hope this now counts as a bug.
I do not think I am allowed to give you my data...

I'll check if the error also occurs with the example data.

**Comment by stela2502** [comment]
Hi again,
The bug persists when following you merge tutorial, too.
See the attached ipynb (zipped as I can not upload the real one here).
[Replicate_scanorama_squidpy_plotting_bug.zip](https://github.com/scverse/squidpy/files/9784079/Replicate_scanorama_squidpy_plotting_bug.zip)

**Comment by stela2502** [comment]
In short just add this after step 8 into the tutorial:
```
import squidpy as sq
sq.pl.spatial_scatter(adata_spatial[adata_spatial.obs['library_id'] == adata_spatial.obs['library_id'].unique()[1] ],
                    color='1700003E24Rik',
                      library_key=adata_spatial.obs['library_id'].unique()[1])
```

**Comment by stela2502** [comment]
The bug becomes even more clear when you try this:
```
sq.pl.spatial_scatter(adata_spatial,
                    color='1700003E24Rik',
                      library_key=adata_spatial.obs['library_id'].unique()[1])
```

**Comment by giovp** [comment]
> The bug becomes even more clear when you try this:
> 
> ```
> sq.pl.spatial_scatter(adata_spatial,
>                     color='1700003E24Rik',
>                       library_key=adata_spatial.obs['library_id'].unique()[1])
> ```

hi @stela2502 ,

so if you are using this function to concatenate
```python
spatial = sc.concat(
    adata,
    label="library_id",
    uns_merge="unique",
    keys=[
        k
        for d in [
            adata[0].uns["spatial"],
            adata[1].uns["spatial"],
            adata[2].uns["spatial"],
            adata[3].uns["spatial"],
        ]
        for k, v in d.items()
    ],
    index_unique="-",
)
```

it means that `library_key="library_id"` and that 
```python
library_id=[adata[0].uns["spatial"], adata[1].uns["spatial"]]
```

If you want to visualize only one slide from your 4 slides dataset, you can use 
```
sq.pl.spatial_scatter(adata, library_key="library_id", library_id="your-library_id", ...)
```

and it should work! Let me know if you manage

**Comment by stela2502** [comment]
The thing is that I do not mind seeing all four plots. It is just that the wrong data is shown on all plots. That is the bug I wanted to highlight. Thank you for the helpful comment.

I wonder why this does not break:
```
sq.pl.spatial_scatter(spatial[spatial.obs['library_id'] == spatial.obs['library_id'].unique()[3] ],
                    color=['SPINK1'],
                    library_key=spatial.obs['library_id'].unique()[3])
```
I have clearly used the library_key incorrectly but this did not throw an error message. Likely as there was only one library_key anyhow.

After trying this with the library_id=
the plot looks like expected, BUT if I do not subset the spatial anndata object first I once again see all the 4 different samples plotted on the one slide now.

```
sq.pl.spatial_scatter(spatial[spatial.obs['library_id'] == spatial.obs['library_id'].unique()[3] ],
                    color=['SPINK1'],
                    library_key=spatial.obs['library_id'].unique()[3],
                    library_id=spatial.obs['library_id'].unique()[3],                  
                     )
# produces the correct output BUT
sq.pl.spatial_scatter(spatial,
                    color=['SPINK1'],
                    library_key=spatial.obs['library_id'].unique()[3],
                    library_id=spatial.obs['library_id'].unique()[3],                  
                     )
#Shows all data points from all 4 slides overlapping on slide nr. 4.
```

So I am sorry this function is still broken.

**Comment by stela2502** [comment]
Hi again. No it does NOT help.
The ISSUE is that even IF I would like to plot only one slide then I would still see alllllll dots from all library_keys/library_ids on this one slide.
I would greatly appreciate if you tried to understand what I want to say with this:
```
sq.pl.spatial_scatter(spatial[spatial.obs['library_id'] == spatial.obs['library_id'].unique()[3] ],
                    color=['SPINK1'],
                    library_key=spatial.obs['library_id'].unique()[3],
                    library_id=spatial.obs['library_id'].unique()[3],                  
                     )
# produces the correct output BUT
sq.pl.spatial_scatter(spatial,
                    color=['SPINK1'],
                    library_key=spatial.obs['library_id'].unique()[3],
                    library_id=spatial.obs['library_id'].unique()[3],                  
                     )
#Shows all data points from all 4 slides overlapping on slide nr. 4.
```

The problem is that THIS makes a difference:
```
spatial[ spatial.obs['library_id'] == spatial.obs['library_id'].unique()[3] ]
```
This plots only the data I want to see but on all slides it plots - even so the other 4 do not contain the cells the data is from! And that is the BUG. The slides not containing the cells/areas should be empty.

Whereas this does plot the correct data, but then again on all slides.
```
spatial
```
This is the real bug. I hope it has become clear now.

What you would need to add to squidpy to make me happy is to make sure that only the cells/areas from one slide are plotted on that slide, not all areas from all the anndata object. I am sure that is a lightweight as the critical part would be to subset the positions with exactly the self.obs['library_id'] == library_key || library_id right before you plot them. This way you could show the correct data on all slides, but only on the correct ones.

To your last answer. Why does squidpy not throw an error if I give it library_key=spatial.obs['library_id'].unique()[3] instead of 'library_id'? And why do I get an error if I leave it empty but it does not throw an error if adata.obs[<library_key>] is not defined as my library_key is actually a library_id? I would class that also as a bug and not a feature...

**Comment by stela2502** [comment]
And sorry - one mistake in my writing: 
```
Whereas this does plot the correct data, but then again on all slides.
```
should of cause read like that
```
Whereas this does plot all data on all slides. And even if I plot only one slide using the library_id then I still see the data from all other slides plotted on this one slide. Mashed into a big bump.

**Comment by giovp** [comment]
> The ISSUE is that even IF I would like to plot only one slide then I would still see alllllll dots from all library_keys/library_ids on this one slide.
I would greatly appreciate if you tried to understand what I want to say with this:

the reason for this is that you shouldn't input subsetted anndata into the function, as explained above.

```
sq.pl.spatial_scatter(spatial[spatial.obs['library_id'] == spatial.obs['library_id'].unique()[3] ],
                    color=['SPINK1'],
                    library_key=spatial.obs['library_id'].unique()[3],
                    library_id=spatial.obs['library_id'].unique()[3],                  
                     )
# produces the correct output BUT
sq.pl.spatial_scatter(spatial,
                    color=['SPINK1'],
                    library_key=spatial.obs['library_id'].unique()[3],
                    library_id=spatial.obs['library_id'].unique()[3],                  
                     )
#Shows all data points from all 4 slides overlapping on slide nr. 4.
```
again, as explained above, these 2 plots produce different behaviour because:
- the first one you are subsetting, and there is some guessing going on that makes the output you expect, but it's completely because of chance.
- the second one it fails because you are passing the same argument to both `library_key` and `library_id` which is not what it expects, again pls check the docstrings

> What you would need to add to squidpy to make me happy is to make sure that only the cells/areas from one slide are plotted on that slide, not all areas from all the anndata object. I am sure that is a lightweight as the critical part would be to subset the positions with exactly the self.obs['library_id'] == library_key || library_id right before you plot them. This way you could show the correct data on all slides, but only on the correct ones.

this is already possible, but it won't work if you subset the object at input. Pls check https://squidpy.readthedocs.io/en/latest/examples.html#plotting

> To your last answer. Why does squidpy not throw an error if I give it library_key=spatial.obs['library_id'].unique()[3] instead of 'library_id'? And why do I get an error if I leave it empty but it does not throw an error if adata.obs[<library_key>] is not defined as my library_key is actually a library_id? I would class that also as a bug and not a feature...

again, as mentioned, it is because there is some guessing going on. We do not have a good way to handle image data in anndata and that's why we resorted with this rather complicated way to have `library_key` and `library_id`. We are gonna refactor it soon to provide a more intuitive interface. For now, simply don't input subsetted anndata to the function and work with the `library_key`, `library_id`.

hth
