### ISSUE TITLE
average on 1 gene per cluster (spatial transcriptomic data)

### ISSUE THREAD

**Issue by sophieRAIBAUD** [scverse/squidpy#614]
## Description

dear all
again thanks for this wonderful package !
I have a spatial transcriptomic data where I created clusters. 
I have a gene of interest and would like to know the mean and variance of this gene of interest in each cluster.
How can I do ?
Many thanks
see an example with a random gene S100A9:
![image](https://user-images.githubusercontent.com/17746001/195712688-83911f09-0229-4805-8e94-9540b4c4aa88.png)

...

**Comment by giovp** [comment]
hi @sophieRAIBAUD ,

thansk for the question, here's a snippet:

```
import squidpy as sq
import scanpy as sc

adata = sq.datasets.visium_hne_adata()
sc.get.obs_df(adata, keys=["Sox7", "cluster"]).groupby(["cluster"]).mean()
sc.get.obs_df(adata, keys=["Sox7", "cluster"]).groupby(["cluster"]).var()
```

hth

I'd kindly ask you to please ask these questions in the discourse: https://discourse.scverse.org/
github issues should only be for bug reports or enhancements requests.

**Comment by sophieRAIBAUD** [comment]
I am sorry 
next tim i post on https://discourse.scverse.org/top?period=quarterly
this solution is just GREAT !!!!!!
