### ISSUE TITLE
About introducing the data to Squidpy

### ISSUE THREAD

**Issue by Pedramto89** [scverse/squidpy#620]
...
To begin with, how we should introduce the data to start the analysis? 
In the tutorial, it's mentioned that loading data is like this:
```python
img = sq.datasets.visium_hne_image()
adata = sq.datasets.visium_hne_adata()
```

Now, for the image, I think it is clear what is the input but for the adata, should we use "filtered_feature_bc_matrix.h5"? Because I used it and got an error.

I used this code:
```python
adata = sq.read.visium(path, counts_file='filtered_feature_bc_matrix.h5',
               library_id=None, load_images=True, source_image_path= "../Data_Analysis/")
```
And then followed by:
```python
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)
sc.tl.umap(adata)
sc.tl.leiden(adata)
```

And finally:
`adata`
 This is what I get:
```python
AnnData object with n_obs × n_vars = 3870 × 17943
    obs: 'in_tissue', 'array_row', 'array_col', 'leiden'
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'spatial', 'log1p', 'pca', 'neighbors', 'umap', 'leiden'
    obsm: 'spatial', 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'
```

But when I want to it, there is an error:
```python
sc.pl.spatial(adata,'leiden',spot_size=1)
```

```pytb
TypeError                                 Traceback (most recent call last)
/var/folders/1m/217nxw_53mg35gpt1pm70hdh0000gn/T/ipykernel_4901/1744331117.py in <module>
----> 1 sc.pl.spatial(adata,'leiden',spot_size=1)

TypeError: spatial() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given
```

@giovp

**Comment by michalk8** [comment]
Hi @Pedramto89 , you should use the Squidpy plotting functions ([sq.pl.spatial_scatter](https://squidpy.readthedocs.io/en/stable/api/squidpy.pl.spatial_scatter.html#squidpy.pl.spatial_scatter) in your case), here's an [example](https://squidpy.readthedocs.io/en/stable/auto_examples/plotting/plot_scatter.html), not the Scanpy one; lmk if this helps.

**Comment by Pedramto89** [comment]
@michalk8 Sorry for the late response. 
Did not work. I again got a huge error.

**Comment by LLehner** [comment]
For reading spatial omics data, please now refer to [spatialdata-io](https://github.com/scverse/spatialdata-io).
