### ISSUE TITLE
`sq.pl.ligrec` Ligand-receptor interaction analysis plotting function error

### ISSUE THREAD

**Issue by idf-io** [scverse/squidpy#622]
## Description

Following your `sq.gr.ligrec` [tutorial](https://squidpy.readthedocs.io/en/stable/auto_examples/graph/compute_ligrec.html) on the [Squidpy documentation](squidpy.readthedocs.io), I received the error below.

## Minimal reproducible example

![image](https://user-images.githubusercontent.com/92318843/201696365-d0fbc862-0fd2-4b9b-8222-08d2cefe4861.png)

```python
import squidpy as sq

adata = sq.datasets.seqfish()
res = sq.gr.ligrec(
    adata,
    n_perms=1000,
    cluster_key="celltype_mapped_refined",
    copy=True,
    use_raw=False,
    transmitter_params={"categories": "ligand"},
    receiver_params={"categories": "receptor"},
)
sq.pl.ligrec(res, source_groups="Erythroid", alpha=0.005)
```

## Version

- I loaded the recommended [conda environment](https://github.com/scverse/squidpy_notebooks/blob/main/environment.yml) as instructed before execution.
- Conda version 1.2.3

Could you lend me a hand in this matter?
Thank you and best regards

**Comment by michalk8** [comment]
Hi @idf-io , please take a look at https://github.com/scverse/squidpy/pull/609
In essence, upgrading `pandas>=1.5.0` should fix your issue.

**Comment by 17843109321** [comment]
I have the same error..and I haven't found a solution yet

**Comment by 17843109321** [comment]
I have the same error..and I haven't found a solution yet

**Comment by 17843109321** [comment]
I have the same error..and I haven't found a solution yet
The relevant software information :
scanpy==1.9.1 anndata==0.8.0 umap==0.5.3 numpy==1.22.4 scipy==1.9.3 pandas==1.5.1 scikit-learn==1.1.3 statsmodels==0.13.5 python-igraph==0.10.2 pynndescent==0.5.8 squidpy==1.2.3

**Comment by michalk8** [comment]
Will look into this tomorrow!

**Comment by hiraksarkar** [comment]
I am getting the exact same error, my configuration is as follows 
```
scanpy==1.9.2 anndata==0.8.0 umap==0.5.3 numpy==1.22.4 scipy==1.10.0 pandas==1.5.3 scikit-learn==1.2.1 statsmodels==0.13.5 python-igraph==0.10.4 pynndescent==0.5.8
squidpy==1.2.3
```

**Comment by michalk8** [comment]
> I am getting the exact same error, my configuration is as follows

Can you try installing the latest version from GitHub? I'm not sure we made a new release since the fix.

**Comment by giovp** [comment]
i don't think we did, would still try from main

**Comment by renyuan1988** [comment]
I met the exact error, and I have installed the latest version of squidpy from github, below are my session info:
scanpy==1.9.3 anndata==0.8.0 umap==0.5.3 numpy==1.21.6 scipy==1.10.1 pandas==1.5.3 scikit-learn==1.2.2 statsmodels==0.13.5 python-igraph==0.10.4 louvain==0.8.0 pynndescent==0.5.8
squidpy==1.2.3
Looking for your directions, many many thanks.
