### ISSUE TITLE
ligrec pvalue and qvalue

### ISSUE THREAD

**Issue by wangjiawen2013** [scverse/squidpy#624]
Hi,
sq.gr.ligrec outputs both three decimal and one decimal pvalue, and there are a lot zeros pvalue, how to increase the decimals and output both pvalue and fdr ? and what does zero pvalues mean ?
![image](https://user-images.githubusercontent.com/29703450/203213119-acad6ce3-0e0a-4a51-a18f-6293108ac36d.png)
![image](https://user-images.githubusercontent.com/29703450/203213163-49cd7d8f-9c3e-4197-ad5f-3c280ff9685a.png)

**Comment by michalk8** [comment]
Hi @wangjiawen2013 , the p-value isn't truncated to 3 decimal points (even though it seems like it), it's just how `pandas` renders the cells in the notebook - the reason for this artifact that the permutation test uses by default `1000` permutations to compute the p-value, increasing `n_perms=...` should have the desired effect.
