### ISSUE TITLE
What is squidpy's license? BSD3 or GPL?

### ISSUE THREAD

**Issue by dani-ham** [scverse/squidpy#626]
Hi

If using PyQt5(GPL License)  then squidpy have to use GPL License isn't it?
ex. squidpy/pl/_interactive/_controller.py
If I am wrong, please let me know.

Thanks.

**Comment by michalk8** [comment]
I should be BSD-3, as defined by the `LICENSE`. I'm not an sure, but seems any GPL-compatible can be used, based on [this](https://riverbankcomputing.com/commercial/license-faq) says that: "If your license is incompatible with the GPL then you need a commercial PyQt license." [and BSD-3](https://www.gnu.org/licenses/license-list.html#ModifiedBSD) seems to be [compatible](https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean) with GPL.
Also, in the future, the Napari viewer is will be deprecated in favor of [scverse/napari-spatialdata](https://github.com/scverse/napari-spatialdata).
Hope this helps.

**Comment by giovp** [comment]
indeed is BSD-3 and is GPL-compatible! closing this feel free to reopen
