### ISSUE TITLE
Quality control in the tutorial with n_cells_by_counts

### ISSUE THREAD

**Issue by pakiessling** [scverse/squidpy#629]
I am having trouble following the Merfish tutorial at https://squidpy.readthedocs.io/en/stable/external_tutorials/tutorial_vizgen.html

There, two histograms are ploted to decide on what cells / genes are to be filtered.
`sns.distplot(adata.obs["total_counts"])` makes sense to me, we plot a histogram of how many spots appear in the cells. Based on that we can select a threshold of cells to kick out that are probably segmentation artefacts.

`sns.distplot(adata.obs["n_genes_by_counts"])` as a plot to decide what genes to exclude does not make sense to me. From my understanding this creates a histogram of how many different genes are found per cell.

Shouldn't this be `sns.distplot(adata.var["n_cells_by_counts"])` to visualize in how many cells each gene is found? 
This would make more sense to justify the `sc.pp.filter_genes(adata, min_cells=10)` filtering.

Am I misunderstanding something?

Thank you!

**Comment by giovp** [comment]
hi @pakiessling ,

apologies for late reply. 

> sns.distplot(adata.obs["n_genes_by_counts"]) as a plot to decide what genes to exclude does not make sense to me. From my understanding this creates a histogram of how many different genes are found per cell.

> Shouldn't this be sns.distplot(adata.var["n_cells_by_counts"]) to visualize in how many cells each gene is found?

I agree, it should have been `"n_cells_by_counts"`. Unfortunately I don't have capacity right now but if you feel like submitting a PR to update the notebook I'd be happy to take a look. Thanks!

You can also take a look at this tutorial on the type of pre-processing that is used
https://squidpy.readthedocs.io/en/stable/external_tutorials/tutorial_vizgen_mouse_liver.html

**Comment by pakiessling** [comment]
@giovp I have created a pull request https://github.com/scverse/squidpy_notebooks/pull/110

Let me know if this works. First time using git 🙈
