### ISSUE TITLE
Difference between scale and spot_scale in squidpy.im.calculate_image_features

### ISSUE THREAD

**Issue by cf98** [scverse/squidpy#630]
While looking at the documentation of calculating image features, I was trying to understand what the scale and spot_scale means. 

In the [Extract image features](https://squidpy.readthedocs.io/en/stable/auto_examples/image/compute_features.html#sphx-glr-auto-examples-image-compute-features-py) document, it says

> Use mask_circle = True, scale = 1, spot_scale = 1, if you would like to get features that are calculated only from tissue in a Visium spot.
> 
> Use scale = X, with X < 1, if you would like to downscale the crop before extracting the features.
> 
> Use spot_scale = X, with X > 1, if you want to extract crops that are X-times the size of the Visium spot.

What does "downscale the crop" mean? I could `understand spot_scale` means, but what does `scale` mean?

Thanks!
...

**Comment by giovp** [comment]
hi @cf98 ,

`scale` is rescaling the actual image, this is useful if the image is very large and you are interested in a lower resolution version or if your spots coordinates are in a different resolution than your image. `spot_scale` instead act on the spot, rescaling the size for the image feature computation. 

hth

**Comment by cf98** [comment]
> 

Thank you!
