### ISSUE TITLE
Some questions about raw spatial data

### ISSUE THREAD

**Issue by HelloWorldLTY** [scverse/squidpy#633]
Hi, I intend to access the raw spatial data of the examples provided by squidpy. Is it possible? I think UMI count based data work for me. Thanks.

**Comment by giovp** [comment]
hi @HelloWorldLTY ,

which example?
thanks

**Comment by HelloWorldLTY** [comment]
Hi, if possible, the more data you provide, the better I can push forward my project. Thanks a lot.
