### ISSUE TITLE
Running Own Dataset with Qpath Output (CODEX) using Squidpy

### ISSUE THREAD

**Issue by DRSEI** [scverse/squidpy#640]
## Description

I am in need of assistance with a Qpath output data file from CODEX. The file is labeled with channel information and X and Y coordinates, but does not include the sample name or tissue name as it is only for one sample. I am having some difficulties with processing this file. I was hoping to utilize the features of Squidpy for file loading, clustering, and cell type etc processing. However, I am not sure if Squidpy is tutorial  CODEX output. I have posted this question on discourse.scverse.org since November of last year but have yet to receive any feedback. I am hoping someone can guide me through the pre-processing steps or even I am  happy to contribute to the development of this feature in the Squidpy package. 
...

**Comment by giovp** [comment]
hi @DRSEI ,
thank you for the interest in squidpy, could you please provide me with some clarification on the problem?
- what is the data type you are tying to input in squidpy?
- what would you like to do with it with squidpy functions?

for importing any type of spatial omics data into a squidpy-compatible anndata I would suggest to take a look at this tutorial https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

thank you

**Comment by DRSEI** [comment]
![Screenshot 2023-02-22 at 6 11 57 am](https://user-images.githubusercontent.com/67427597/220448253-07654bb7-c97b-4e9b-bc3d-be9c1475fa1a.png)
@giovp Thank you for taking the time to respond to my comments. I would like to clarify that I am using CODEX output and have segmented it using Qpath. The file includes x and y coordinates with gene/protein expression matrices for annotated markers in CSV format. I am happy to share these files with you and have attached a print screen of the data type.

I am interested in running image segmentation, standard clustering, and cell type annotation.(https://squidpy.readthedocs.io/en/latest/external_tutorials/tutorial_vizgen.html) However, I require guidance on how to convert my data and load into squidpy or annadata. I would greatly appreciate it if you could provide me with some assistance.

Also, I was wondering if you have any tutorials on this type of output from CODEX. If you do, I would be interested in taking a look.

Thank you again for your help.

**Comment by wangjiawen2013** [comment]
Maybe pysodb can help!
https://github.com/scverse/squidpy/issues/576

**Comment by DRSEI** [comment]
Thank you, i am going to try out.

**Comment by giovp** [comment]
hi @DRSEI ,
this might be useful for you: https://squidpy.readthedocs.io/en/latest/auto_tutorials/tutorial_read_spatial.html

but also what @wangjiawen2013 suggested!

**Comment by wangjiawen2013** [comment]
Seurat supports CODEX very well now: https://satijalab.org/seurat/articles/seurat5_spatial_vignette_2.html

**Comment by LLehner** [comment]
Hi @DRSEI, @wangjiawen2013 

CODEX formatted files can now also be used with Squidpy, by using [spatialdata-io](https://github.com/scverse/spatialdata-io), which is now used for readers of spatial-omics technologies.

first install latest development version of spatialdata-io:
```pip install git+https://github.com/scverse/spatialdata-io.git@main```

then import spatialdata_io and load the data:
```
import spatialdata_io

sdata = spatialdata_io.codex(path="path/to/directory/")

adata = sdata.table
```

**Comment by DRSEI** [comment]
@LLehner  Thank you so much
