### ISSUE TITLE
FOVs wrongly taken into account for spatial neighborhood calculation

### ISSUE THREAD

**Issue by SaskiaFreytag** [scverse/squidpy#642]
It appears to me that when data is in FOVs (Nanostring CosMX data) the spatial neighbors are calculated wrongly. I get many more neighbors between distant FOVs than within the FOV. This seems wrong.

**Comment by giovp** [comment]
Hi @SaskiaFreytag , thank you for the interest in squidpy. Could you please clarify the issue by providing a reprex (reproducible example) or attaching a piece of code that could help me understand the bug?

thank you

**Comment by giovp** [comment]
I believe this issue is that you need to pass the `library_key` to the `spatial_neighbor` function in order to compute neighbors graph only on points belonging to the same fov. Closing this but feel free to reopen if necessary
