### ISSUE TITLE
`sq.pl.extract` doesn't work with `ArrayView` objects

### ISSUE THREAD

**Issue by alam-shahul** [scverse/squidpy#646]
## Description

Sometimes I have `AnnData` objects with `ArrayView` objects in the `.obsm` field, but if I use `sq.pl.extract` on those objects, this results in `NaN` columns in the `.obs` field of the resulting object.

## Minimal reproducible example

It is difficult to reproduce because I am not sure why there are `ArrayView` objects in my `AnnData`, but I find that if they are there, then `sq.pl.extract` will fail in this way.

## Version

`'1.2.3'`

**Comment by giovp** [comment]
hi @alam-shahul ,

the array view happens if you have a "view" of an anndata, e.g.

```python
adata_view = adata[:,0:10] # this is a view
adata_copy = adata[:,0:10].copy() # this is not a view
```

I'm not sure we'll be able to support extract on views I'm afraid
