### ISSUE TITLE
Tiling/combining FOVs in spatial plots

### ISSUE THREAD

**Issue by lamdan2** [scverse/squidpy#651]
If you have multiple FOVs from a single tissue section, spatial plots (spatial_scatter,spatial_segment) will plot each FOV in a separate panel. Is there any way to override this behaviour and plot all the FOVs in a single image? I tried to create a "dummy" adata.obs and pass it as library_id, but I couldn't get that to work, presumably due to the existing mappings between FOVs and spatial coordinates
...

**Comment by giovp** [comment]
unfortunately it's not possible but we are working on a solution in spatialdata. I will keep this opena and try to remember to link to the appropriate example here.

**Comment by giovp** [comment]
I would suggest you to take a look at the spatialdata-plot static plotting library https://github.com/scverse/spatialdata-plot
