### ISSUE TITLE
Is that possible to redefine the cell boundaries for Nanostring data? Thanks

### ISSUE THREAD

**Issue by yingsun-ucsd** [scverse/squidpy#654]
Hi, I am using squidgy with some Nanostring data and it works great. One thing I would like to try is to define the cell boundaries by myself.  Dose Squidpy have a such function? If so, would you please direct me to the material/instructions about how to do so? Thanks.
...

**Comment by giovp** [comment]
hi @yingsun-ucsd 

could you elaborate on what you mean by redefining cell boundaries? I'm, not sure what you mean but I believe we do not have such a function.

**Comment by yingsun-ucsd** [comment]
I uploaded an image and you can see some cell boundaries might not be right (some examples are marked with a red arrow). I am trying to find a way to correct this issue since that might affect the gene expression with cells. Thanks.

![Picture1](https://user-images.githubusercontent.com/29928188/227286290-2e45c523-0719-4dad-9421-6262e18374c3.png)

**Comment by giovp** [comment]
I think you'd hjave to revisit and improve the segmentation step of the data processing pipeline. Closing this as it is not specific issue to squidpy
