### ISSUE TITLE
Ingest data from different tissues

### ISSUE THREAD

**Issue by georgezakinih** [scverse/squidpy#667]
Thanks for the very useful package!

I have a use case where I need to combine multiple single cell datasets where every dataset come from a different MxIF tissue. In this case, the spatial coordinates can't be combined together in the annData object (otherwise the spatial graph might connect two cells that are in different tissues but happen to have close coordinates). Is there currently a feature in squidpy to handle this use case?
...

**Comment by georgezakinih** [comment]
Hi everybody, I appreciate your thoughts on the message above.

**Comment by giovp** [comment]
hi @georgezakinih ,
apologies for very late reply, and thank you for your interest in squidpy. 

>  In this case, the spatial coordinates can't be combined together in the annData object (otherwise the spatial graph might connect two cells that are in different tissues but happen to have close coordinates

in fact, if it's only about the spatial coordiantes, we can handle it, please take a look at the `library_key` value in the function signature of the `spatial_neighbor` function https://squidpy.readthedocs.io/en/latest/api/squidpy.gr.spatial_neighbors.html#squidpy.gr.spatial_neighbors

you can create an anndata for each slide, then concatenate them all with `uns_merge="unique"` with `anndata.concat` and then the label key would be the `library_key` argument in the function signature. 

Building a spatial graph like that basically generate a block diagonal sparse adjacency matrix which can be directly used for functions downstream.

**Comment by georgezakinih** [comment]
Thanks @giovp. I appreciate the guidance.
