### ISSUE TITLE
interactive error

### ISSUE THREAD

**Issue by Ketomihine** [scverse/squidpy#675]
## Description

Hello, thanks for developing Squidpy！！！

My problem:

When i ran  viewer = img.interactive(adata),  Squidpy generated an error

WARNING: could not connect to display 
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.

then，jupyterhub generated error: Kernal Restarting

## Minimal reproducible example

```python
import squidpy as sq
# load the pre-processed dataset
adata = sq.datasets.visium_hne_adata()
sq.pl.spatial_scatter(adata, color="cluster")
img = sq.im.ImageContainer.from_adata(adata,
    img_key="hires",
    library_id="V1_Adult_Mouse_Brain"
)
viewer = img.interactive(adata)
```

## Traceback

<details>

```pytb
WARNING: could not connect to display 
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
```

</details>

## Version

squidpy==1.2.2

**Comment by giovp** [comment]
hi @Ketomihine ,

thanks for your interest in squidpy, I am currently unable to look into this, I'm afraid is something that might be related to installation issues so I would suggest to reinstall squidpy in a fresh conda environment

**Comment by wallet-maker** [comment]
I am experiencing the same error with fresh and minimal conda environments

minimal environment setup:
```
conda create --name 2023_squidpy
conda activate 2023_squidpy
conda install -c anaconda pip
pip install 'squidpy[interactive]  `#as suggested here: https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_napari.html
conda install -c anaconda jupyter
```

When I run the example code from the tutorial I can reproduce the error above (I'm also getting this with my own data):

```
import squidpy as sq
adata = sq.datasets.visium_hne_adata()
img = sq.datasets.visium_hne_image()
viewer = img.interactive(adata)
```

I also tried downgrading squidpy from 1.3.0 to 1.2.2 , the version used in the tutorial above, but it did not help.

It would be great if you could help me fix this or find a workaround.

**Comment by LLehner** [comment]
Image container usage in squidpy will be deprecated eventually. I would recommend to use [napari-spatialdata](https://github.com/scverse/napari-spatialdata) ```Interactive(sdata)```, where ```sdata``` is a [spatialdata](https://github.com/scverse/spatialdata) object, instead.
