### ISSUE TITLE
Thoughts on rescaling the adata.obsm['spatial'] to match spatial image size of two replicates.

### ISSUE THREAD

**Issue by jeji0209** [scverse/squidpy#677]
Hi, thank you for developing this excellent tool.
I have two 10x Visium spatial replicates from the same sample (adjacent slides).
My initial plan was to integrate the two replicates via SCVI, then look at the sample as one integrated data. 
However, I the two replicates I have were produced on different image size, therefore their spatial coordinates range and scale factors are very different, and one plot comes out much smaller than the other when using the sc.pl.spatial() function.
My idea was to readjust the smaller spatial data by multiplying all adata.obsm['spatial'] by a specific number, so it will be similar to the bigger spatial data, and ignore the image. My code looks something like this:

```
# Rescaling
adata_1.obsm['spatial'][:,0] = adata_1.obsm['spatial'][:,0] * 3.2336716681376876
adata_1.obsm['spatial'][:,1] = adata_1.obsm['spatial'][:,1] * 2.7973800971899427

#Integrate via SCVI to make 'condat_data'

#Plotting
sc.pl.spatial(concat_data[concat_data.obs["library_id"] == "sample_1"], library_id = 'sample_1',color="leiden", spot_size=800, img_key = None)
sc.pl.spatial(concat_data[concat_data.obs["library_id"] == "sample_2"], library_id = 'sample_2',color="leiden", spot_size=800, img_key = None)
```
My concerns here is that this rescaling of obsm data is not appropriate when conducting downstream analysis via squidpy such as building spatial neighbors, as it only rescaled the obsm data for visualization, and did not consider adata.uns['spatial'].
Any thoughts or solution regarding this situation?

Thank you in advance :)

**Comment by giovp** [comment]
hi @jeji0209 if you build the spatial_neighbors with `library_key` argument pointing to the column in anndata where the information about each visium slide is present, the spatial graph will be built considering each slide separately. Regarding the rescaling of the coordinates, I believe this is an analysis question specific to your data, and I don't really know how to help you there. Closing this but feel free to reopen
