### ISSUE TITLE
segmentation_area_mean

### ISSUE THREAD

**Issue by WT215** [scverse/squidpy#691]
According to [https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.regionprops](https://scikit-image.org/docs/stable/api/skimage.measure.html#skimage.measure.regionprops), `segmentation_area_mean` returned from `sq.im.calculate_image_features` means `number of pixels of the region scaled by pixel-area.`. But I am confused by the `mean`, does it scaled by the total number of nuclei in a visium spot?

Many thanks!
...

**Comment by giovp** [comment]
hi @WT215 indeed it's the average of the total number of nuclei contained in the spot.
