### ISSUE TITLE
Raw counts not found in the example slide-seqv2 data

### ISSUE THREAD

**Issue by MingzeDong** [scverse/squidpy#695]
Hi, I am trying to use the example slideseqv2 data in Squidpy, starting from raw counts. However, the returned adata has a raw.X but it is actually the preprocessed version after some lib normalization and log1p transform. I wonder if you are able to provide a new version of the data with the raw counts correctly placed in adata.raw.X. Thank you so much!

**Comment by giovp** [comment]
hi @MingzeDong , unfortunately we only provide the normalized counts, I'd suggest you to take a look at the original publication for raw data
