### ISSUE TITLE
compare 2 regions on the same 10x Visium capture area

### ISSUE THREAD

**Issue by cathalgking** [scverse/squidpy#696]
Is it possible to use squidpy to subset regions on a 10x Visium capture area for comparison? I have a tissue section that has some part tumour and the rest not. I am interested in subsetting the tumour region that is drawn on by the pathologist in the spatial image. Or is there some other way to do this? thanks

**Comment by giovp** [comment]
it is possible, by for instance subsetting the anndata based on the annotation. A maybe better approach that fits your case is using the binding box query in spatialdata https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/spatial_query.html
