### ISSUE TITLE
Crop or subset Visium image plot

### ISSUE THREAD

**Issue by cathalgking** [scverse/squidpy#710]
I am using Squidpy to plot a 10x Visium image with spatial data overlayed, as shown below using the below code. Is there a way to automatically crop the plot to only show the spots below tissue. I know there is the `crop_coord` option in the below function but I would like to automatically crop the image based on where the tissue is, or that approximate region. Is that possible? The Seurat package does this quite well for example.
`sq.pl.spatial_scatter(A1, color=["Zg16"])`
<img width="717" alt="Screen Shot 2023-06-16 at 3 53 44 pm" src="https://github.com/scverse/squidpy/assets/32261323/00b6562a-f37d-41e0-acb2-69b2fe2e28b5">

**Comment by cathalgking** [comment]
@giovp Just following up here - Is there any possibility to do this?

**Comment by giovp** [comment]
hi @cathalgking unfortunately we don't have that functionality. I understand it would be very useful but I don't have capacity to work on it atm and in the foreseeable future, if you are interested in submitting a PR it would be very welcome
