### ISSUE TITLE
ask help for dataset input 

### ISSUE THREAD

**Issue by Ding7928** [scverse/squidpy#712]
To begin with, how we should introduce the data to start the analysis? In the tutorial, it's mentioned that loading data is like this:

```
img = sq.datasets.visium_hne_image()
adata = sq.datasets.visium_hne_adata()
```

Now, I would like to try using dataset of Human Colorectal Cancer(https://www.10xgenomics.com/resources/datasets/human-colorectal-cancer-11-mm-capture-area-ffpe-2-standard), should we use "CytAssist_11mm_FFPE_Human_Colorectal_Cancer_filtered_feature_bc_matrix.h5”? Because I used it and got an error.
I used this code:

```
data = sq.read.visium(path = 'colorectal_data/CytAssist_11mm_FFPE_Human_Colorectal_Cancer_filtered_feature_bc_matrix.h5', counts_file='CytAssist_11mm_FFPE_Human_Colorectal_Cancer_filtered_feature_bc_matrix.h5',
               library_id=None, load_images=True, source_image_path= "colorectal_data/spatial/")
```
i got error

**Comment by Ding7928** [comment]
@giovp

**Comment by Ding7928** [comment]
> > i got error
> 
> Hi @Ding7928 , could you please post the error traceback below?

hi, thanks for replying! i already solved it.

**Comment by LLehner** [comment]
In case someone else has the same question and is looking here: If you read visium files with ```sq.read.visium()``` you need to specify the path to the *root directory* containing all the visium files, not the path to an individual file such as the count matrix. The count matrix is specified with the ```counts_file``` parameter. See [here ](https://squidpy.readthedocs.io/en/latest/api/squidpy.read.visium.html) for how to use the method. 

Also the code from the tutorials
```
img = sq.datasets.visium_hne_image()
adata = sq.datasets.visium_hne_adata()
```
is specifically for loading pre-processed example data sets and not for reading in files.
