### ISSUE TITLE
Nanostring FOV order

### ISSUE THREAD

**Issue by jnmark** [scverse/squidpy#715]
I am following the Nanostring tutorial https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_nanostring.html and was specifically referring to the section 'Visualize annotation on UMAP and spatial coordinates:

```
sq.pl.spatial_segment(
    adata,
    color="Max.PanCK",
    library_key="fov",
    seg_cell_id="cell_ID",
)
```
I was wondering if there is a way to specify order of FOVs displayed. Currently, it is arranged by lexicographic order instead of ascending, and it would be more intuitive to display ascending order or have the flexibility to specify one. Thanks!

**Comment by giovp** [comment]
hi, I believe you can do that by simply passing the `library_key` in the order you desired, HTH
