### ISSUE TITLE
'module object' is not callable 

### ISSUE THREAD

**Issue by amorje** [scverse/squidpy#720]
...
unable to call squidpy, receiving

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amoghmorje/Documents/GitHub/Squidpy-testing/squidpy.py", line 15, in <module>
    adata = ad(d)
TypeError: 'module' object is not callable

**Comment by amorje** [comment]
import squidpy as sqpython
from anndata import AnnData
import anndata as ad
import pandas as pd


data = pd.read_csv('path')
d = data[['DNA1', 'ECAD', 'CD45', 'CD4', 'CD3D', 'CD8A', 'CD45R',
       'KI67',]]

m = data[['CellID','X_centroid', 'Y_centroid', 'Area', 'MajorAxisLength',
'MinorAxisLength', 'Eccentricity', 'Solidity', 'Extent', 'Orientation']]
spatial = data[['X_centroid', 'Y_centroid']]

adata = ad(d)
adata.obs = m
adata.obsm={"spatial": spatial}

# write 
adata.write('/path')

# read
bdata = ad.read('path')

running those code results in 

in <module>
    import squidpy as sqpython
  File "path", line 15, in <module>
    adata = ad(d)
TypeError: 'module' object is not callable

**Comment by giovp** [comment]
you are importing 
```python
import anndata as ad
```

and then calling the module in 

```python
adata = ad(d)
```
not sure what you are trying to do but please see error message. Unrealted to squidpy, will close
