### ISSUE TITLE
Bug about sq.im.ImageContainer() function in WSL2-VScode

### ISSUE THREAD

**Issue by yunbokai** [scverse/squidpy#721]
## Description
Hi, When I ran the code
```
img=sq.im.ImageContainer(adata_st.uns['spatial']['T91']["images"]['hires'],library_id='T91')
viewer = img.interactive(adata_st)
```
I only get a black GUI, I'm not sure is it correlated with my WSL2-Ubuntu20.04? Could you please give me some advice? 
<img width="798" alt="image" src="https://github.com/scverse/squidpy/assets/94819980/f86576df-fd83-4291-b30b-a4b6c2f9a2ac">

Thanks!

## Version

scanpy==1.9.3 
anndata==0.9.1 
umap==0.5.3 
numpy==1.22.4 
scipy==1.10.1 
pandas==2.0.3 
scikit-learn==1.2.1 
statsmodels==0.14.0 
python-igraph==0.10.5 
pynndescent==0.5.10
squidpy==1.2.3
tangram==0.4.0

...

**Comment by giovp** [comment]
hi @yunbokai unforutnately I have no clue and don't have capacity to test with WSL, not sure if you found a solution already?
