### ISSUE TITLE
using squidpy native datasets 

### ISSUE THREAD

**Issue by amorje** [scverse/squidpy#722]
## Description

was unable to load datasets which are included in squidpy (visium_hne_adata())

...

## Minimal reproducible example

import squidpy as sq

adata = sq.datasets.visium_hne_adata()
img = sq.datasets.visium_hne_image()

```python
...
```

## Traceback

 adata = sq.datasets.visium_hne_adata()
AttributeError: module 'squidpy' has no attribute 'datasets'

```pytb
...
```

</details>

## Version

...

**Comment by LLehner** [comment]
Hi @amorje thank you for your interest in Squidpy.

I couldn't reproduce your error with the latest version 1.3.0 of Squidpy. Which Squidpy version are you running?
