### ISSUE TITLE
sq.pl.spatial_scatter() does not produce hex grid, only background image

### ISSUE THREAD

**Issue by tsvvas** [scverse/squidpy#724]
Hi squidpy team,

Thank you for a great tool!

I am trying to use squidpy for the analysis of spatial transcriptomics data. The issue I have is when I try running sq.pl.spatial_scatter() it outputs an image with background, but it doesn't display the calculated scatterplot for some reason.

The way I run the command. Note that I use gray colormap to see any color hex points.

```python
sq.pl.spatial_scatter(
    adata,
    shape="hex",
    library_id="1",
    color=["dapi"],
    img_cmap="gray"
)
```
This command produces neither error, no warning.

![image](https://github.com/scverse/squidpy/assets/56478746/3e1d6a0f-07a1-493e-b226-3bfb4d839a5c)

What could be the problem?

Thank you in advance.

Best regards,
Vasily Tsvetkov

**Comment by tsvvas** [comment]
P.S. The toy example provided in the [tutorial](https://github.com/theislab/spatial_scog_workshop_2022/blob/main/squidpy/1_tutorial_spatial_adata.ipynb) works, so I used it to construct minimal example.

I discarded fields that are not needed for spatial_scatter and produced an object, containing the matrix, spatial coordinates, image and scaling factors. Inspecting the object I found out that my coordinates had different dtype ("int64" vs "float64" in toy example), but changing dtype in toy example didn't break the output.

If I use matplotlib, it produces a normal scatterplot based on the spatial coordinates.

Here is [the minimal data object](https://drive.google.com/file/d/1Ql0XgHlVlJ7PDOrWqcR0rxuPFZb_7GoI/view) to reproduce the behaviour.

**Comment by tsvvas** [comment]
Hi @michalk8 !

Thank you very much! It appears that the issue was indeed related to size. Now, the spatial_scatter function is working, but it generates too many points, resulting in a messy plot compared to the [tutorial](https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_visium_fluo.html).
<img width="597" alt="My scatterplot" src="https://github.com/scverse/squidpy/assets/56478746/6f7bfcdb-cb11-4add-aa66-2a79b09e43f8">

I suspect the function is plotting all ~30k dots on the single image, instead of only those belonging to the specific field of view. Is there a way to modify this behavior?

DAPI in the original object is not all NaNs, It seems I made an error when copying anndata fields. I have updated [the minimal object with the correct values](https://drive.google.com/file/d/1tgF9TbIU41Ow3HXDECy0imh5Tw9W90_j/view?usp=sharing) in DAPI, just in case.

**Comment by giovp** [comment]
> I suspect the function is plotting all ~30k dots on the single image, instead of only those belonging to the specific field of view. Is there a way to modify this behavior?

yes, you need to specify `library_key` which is the column name for the library_id, please take a look at the tutorial and the docstrings.

**Comment by tsvvas** [comment]
Thank you a lot! I just started with the analysis, and it was not quite clear from the tutorial. Thank you for the answering all my questions.
