### ISSUE TITLE
Co_occurence and Nhood_Enrichment plots question

### ISSUE THREAD

**Issue by meaksu** [scverse/squidpy#729]
When running the co-occurence and neighborhood enrichment plots on multiple samples, is it valid to compare to compare visually these results across samples even though the scales are different for each sample? Or do the plots need to be set to a common scale in order to make any conclusions?

**Comment by giovp** [comment]
thank you for your question I don't think it's valid, you'd have to re scale the scores or aggregate them but I don't have a best practice that I could suggest
