### ISSUE TITLE
ConnectionError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Read timed out.

### ISSUE THREAD

**Issue by Biomamba** [scverse/squidpy#734]
...
Dear Author:
    Thank you for your great toolkit for spatial omics.
   When I run the code, I met this question. Could you please tell me how to figure out it?
`sq.gr.ligrec(
    adata,
    n_perms=100,
    cluster_key="celltype_mapped_refined",
)
sq.pl.ligrec(
    adata,
    cluster_key="celltype_mapped_refined",
    source_groups="Lateral plate mesoderm",
    target_groups=["Intermediate mesoderm", "Allantois"],
    means_range=(0.3, np.inf),
    alpha=1e-4,
    swap_axes=True,
)`

ConnectionError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Read timed out.

By the way, I can't fetch the test data sometimes.
`adata = sq.datasets.seqfish()`

**Comment by giovp** [comment]
hi @Biomamba I would open this issue in omnipath.
