### ISSUE TITLE
transparents spatial spots for zero counts

### ISSUE THREAD

**Issue by cathalgking** [scverse/squidpy#736]
I would like to have transparent spots for spots that have zero counts (or near zero) on a spatial scatter plot. I was trying the function squidpy.pl.spatial_scatter. An example shown below for a 10x Visium dataset. Can this be done?

**Comment by giovp** [comment]
yes, just pass a colormap that can do that for you, you can find how to build such colormap here: https://matplotlib.org/stable/tutorials/colors/colormaps.html

**Comment by cathalgking** [comment]
Ok. Can you show a simple example?
