### ISSUE TITLE
Choosing a radius for sq.gr.spatial_neighbors - What are the units? What are some suggested values?

### ISSUE THREAD

**Issue by mlotstein44** [scverse/squidpy#740]
I'm analyzing Nanostring CosMx data using squidpy and I'm computing a spatial neighbors graph using `sq.gr.spatial_neighbors`. I want to get all of the spots within a specified radius, but I don't see any information on what units the radius should be in and the recommended radius range. 

The code that I'm currently using is
`sq.gr.spatial_neighbors(adata, radius=100, coord_type="generic")`

I'm not sure if the value that I've chosen (100 in this case) is in pixels, um, etc. Is there any way to test this? Or is the radius standardly in a particular unit?

I've been looking at this squidpy page https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_nanostring.html#neighbors-enrichment-analysis (under the Building the Spatial Neighbors Graphs section) and I see that they use a radius of 30. Although I'm still not sure what units that is in either. 

Any advice on this issue would be appreciated! Thank you.

**Comment by LLehner** [comment]
Hi @mlotstein44,

a nearest neighbor tree is calculated using the radius. The radius is just a (euclidean) distance between some coordinate pairs. The exact unit would depend on your data.
