### ISSUE TITLE
Would it be possible to set default filenames for read.vizgen and read.nanostring similiar to read.visium?

### ISSUE THREAD

**Issue by pakiessling** [scverse/squidpy#744]
https://github.com/scverse/squidpy/blob/8cd23551e5e14a95ae769d426c33813e5d889179/src/squidpy/read/_read.py#L107

Vizgen has always used `cell_by_gene.csv` and `cell_metadata.csv` for counts_file and meta_file respectively.

**Comment by giovp** [comment]
hi @pakiessling thanks a lot for this, from our experience with the 10x format, these can be renamed with various versions of the library, hence I wouldn't want to do it
