### ISSUE TITLE
How to read nanostring Geomx DSP data

### ISSUE THREAD

**Issue by jwoods9** [scverse/squidpy#748]
It seems that the nanostring tutorial is specific to CosMx data. Is there a way to analyze GeoMx DSP data? I'm having trouble figuring out how to make an AnnData object. Any help would be greatly appreciated. Thanks!

**Comment by HollyRafique** [comment]
did you make any progress on this? not sure if squidpy is even the right tool for GeoMx but would be interested to hear from anyone who found a way to make it work?

**Comment by giovp** [comment]
hi, we do not and will not support geomx data, apologies. If you are interested in implementing a reader, I would suggest to do it in spatialdata-io https://spatialdata.scverse.org/projects/io/en/latest/index.html
