### ISSUE TITLE
sq.pl.spatial_scatter() for stereo-seq without .uns['spatial']

### ISSUE THREAD

**Issue by YuchiQiu** [scverse/squidpy#749]
Hi, I am using Squidpy to generate scatter plot for stereo-seq datasets. However, there is no .uns['spatial'] for the data. 

I tried to force the plot without the image:
`sq.pl.spatial_scatter(adata,img=False,color=['Fgf9'])`

But I still got the error "Spatial key 'spatial' not found in `adata.uns`."

As stated in the documentation: If no image is plotted, it defaults to a scatter plot, see `matplotlib.axes.Axes.scatter()`
So what do I miss to plot the scatter without image? 

Thank you.
...

**Comment by giovp** [comment]
you need to pass the argument `shape=None`
