### ISSUE TITLE
Xenium image and segmentation

### ISSUE THREAD

**Issue by Pointillomic** [scverse/squidpy#754]
Hello,

Thank you for this amazing tool! It has been so helpful in dealing with spatial data, especially in a way that is reasonable in terms of memory and resources.

I was wondering if there were plans of making a read.xenium function that would import the image and segmentation information into the anndata structure, similar to the read.nanostring function. The current xenium tutorial excludes the image and segmentations

Any help with this would be greatly appreciated!

**Comment by LucaMarconato** [comment]
Hi @Pointillomic, we developed a function to read Xenium data in the [spatialdata-io](https://github.com/scverse/spatialdata-io) package. We are gradually transitioning in using the new data structure `[SpatialData](https://github.com/scverse/spatialdata/)` in place of `AnnData`. Anyway `SpatialData` contains an `AnnData` object inside so you can easily adapt `AnnData` based workflows.
