### ISSUE TITLE
Visualize adata interactively with Napari

### ISSUE THREAD

**Issue by zhenghu159** [scverse/squidpy#762]
Hello，
I want to visualize adata interactively with Napari, but I don't have image to generate ImageContainer object, such as MERFISH data. I follow [this turorial](https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_napari.html). How can I visualize adata using Napari without ImageContainer object?
Like this figure:
![figure](https://squidpy.readthedocs.io/en/stable/_images/2c98b41f777070b014419c30e7a7618a88a55029d2214378552eb3937e155b78.png)
...

**Comment by giovp** [comment]
hi @zhenghu159 , thanks for the interest, unfortunately we don't have functionality for 3D of that case in napari. It will be possible to be done with https://github.com/scverse/napari-spatialdata but we don't have a tutorial for that atm, but watch that space!
