### ISSUE TITLE
Any existing effort to port squidpy functionalities to R?

### ISSUE THREAD

**Issue by stemangiola** [scverse/squidpy#787]
Hello All,

I was wondering if there is any effort to port some of the squidpy tools (e.g. segmentation) to R.

For example as Velociraptor R package does for scvelo.

My discourse post is here: https://discourse.scverse.org/t/any-existing-effort-to-port-squidpy-functionalities-to-r/1983

Thanks a lot.
Stefano

**Comment by LLehner** [comment]
Hi @stemangiola, no we don't plan to port squidpy functionalities to R. I mean segmentation itself is not done with squidpy, maybe the authors of the segmentation packages would be up for it, but i don't really see a good reason to do that.
