### ISSUE TITLE
dated napari tutorial/documentation

### ISSUE THREAD

**Issue by LinearParadox** [scverse/squidpy#805]
Hi all,

I believe the napari documentation is a bit dated. Specifically, using it how it is [written here](https://squidpy.readthedocs.io/en/stable/notebooks/tutorials/tutorial_napari.html), throws an error saying that napari is deprecated. More specifically this line:
```
viewer = img.interactive(adata)
```

Is this part of a broader move to the spatial data format/ecosystem? I'm a bit new to the spatial transcriptomics field (and mostly have done single cell previously), and apologize if this is a naive question.

Thank you all for the great tool!

**Comment by giovp** [comment]
indeed, we are not maintaining the napari integration in squidpy and only gonna support the napari-spatialdata integration. https://github.com/scverse/napari-spatialdata
