### ISSUE TITLE
pl.ligrec Value Error when following seqFish tutorial notebook

### ISSUE THREAD

**Issue by DuncanBrady** [scverse/squidpy#808]
## Description
Upon running the the pl.ligrec in seqFish tutorial notebook the following error appears.

<img width="1559" alt="image" src="https://github.com/scverse/squidpy/assets/53142515/c78996f0-073d-43fd-a411-76fd68ff6205">

## Minimal reproducible example
The bug can be reproduced running the squidpy seqFish tutorial found here, 
https://github.com/scverse/squidpy_notebooks/blob/main/tutorials/tutorial_seqfish.ipynb
The env link in the tutorial doesnt work, but my current env as displayed by the notebook is as follows

<img width="1826" alt="image" src="https://github.com/scverse/squidpy/assets/53142515/ec987116-1193-421e-b707-c176c7e4bd9e">

**Comment by DuncanBrady** [comment]
Hi @giovp, I am using version 1.4.1 of squidpy which is the most recent version available through pip, initially I tried to use conda to install but the version on conda forge is 1.2.3.

**Comment by DuncanBrady** [comment]
Update, the tutorial appears to be running now, despite not changing anything. I can no longer replicate the issue

**Comment by DuncanBrady** [comment]
I have just re-tested the code and it is working now, I have not changed anything but can no longer reproduce the error

**Comment by giovp** [comment]
thanks!
