### ISSUE TITLE
The Kernel crashed while executing code in the current cell

### ISSUE THREAD

**Issue by spatts14** [scverse/squidpy#812]
Hi! Thanks for writing Squidpy! Its really amazing!

I'm running into an issue and I'm not sure if its an issue with squidpy itself or how I'm running the code or space on my computer. I cannot run sq.gr.ligrec or sq.gr.spatial_autocorr without my kernel crashing. Is there something I am missing? Do I need to run this on the HPC? 

Info about my data:
- Xenium data
- adata object is n_obs × n_vars = 53466 × 339
- The size of the object is: 100039055 bytes (code: sys.getsizeof(adata))
- The size of the object is: 151294272 bytes ( code: asizeof.asizeof(adata))

I've tried reducing my dataset to 0.2 and reducing the permutation to as low as 2 just to try to get it to work but every time I get the miss error: 

The Kernel crashed while executing code in the current cell or a previous cell. 

Please review the code in the cell(s) to identify a possible cause of the failure. 

Here is the code I'm running

```
adata_subsample = sc.pp.subsample(adata, fraction=0.2, copy=True)
sq.gr.spatial_neighbors(adata_subsample, coord_type="generic", delaunay=True)
res = sq.gr.ligrec(
    adata,
    n_perms=2,
    cluster_key="new_clusters",
    copy=True,
    use_raw=False,
    transmitter_params={"categories": "ligand"},
    receiver_params={"categories": "receptor"},
)
```

and with the Moran I

```
adata_subsample = sc.pp.subsample(adata, fraction=0.2, copy=True)
sq.gr.spatial_neighbors(adata_subsample, coord_type="generic", delaunay=True)

sq.gr.spatial_autocorr(
    adata_subsample,
    mode="moran",
    n_perms=10,
    n_jobs=1,
)
adata_subsample.uns["moranI"].head(10)
```
...

Any suggestions would be really helpful!

**Comment by Rafael-Silva-Oliveira** [comment]
Also having the same issue with VisiumHD data (140k + spots/barcodes with over 15k genes)

Perhaps it isn't optimized to support over 20-30k spots and so it crashes due to memory issues?

**Comment by LLehner** [comment]
Hi @spatts14, @Rafael-Silva-Oliveira,

squidpy should be able to handle data sets of the size you mention. When the kernel crashes, is there any error message? Perhaps this is a RAM issue? Does it also happen if you run it on a machine with more RAM?

**Comment by spatts14** [comment]
I think there was an issue with my conda environments. I had to uninstall anaconda and redownload and recreate my environments.
