### ISSUE TITLE
add zarr.zip to adata

### ISSUE THREAD

**Issue by rkulchar** [scverse/squidpy#814]
Hi! It would be nice to be able to plot the outline of the cell, as opposed to only the x and y centroids, in sq.pl.spatial_scatter (this is usually .zarr.zip) for spatial. Is there a way to do this?

**Comment by giovp** [comment]
yes, it' `sq.pl.spatial_segment` for labels, if you are referring to polygons, then that is not possible, I would suggest you take a look at https://spatialdata.scverse.org/projects/plot/en/stable/plotting.html
