### ISSUE TITLE
Should the raw H&E image (.tif) and the image stored in anndata be in the same orientation?

### ISSUE THREAD

**Issue by ddzhang3** [scverse/squidpy#818]
- While utilizing the `squidpy.im.calculate_image_features()` function to calculate image feature on `anndata` object  with an `squidpy.im.ImageContainer`, constructed by employing a raw hematoxylin and eosin (H&E) stained image file in TIF format, which is approximately 500MB in size, I've encountered a discrepancy where the image encapsulated within the anndata appears to be either flipped or rotated relative to the original H&E image. I am seeking clarification on whether such a transformation could potentially introduce any complications or inaccuracies in the image feature calculation  process.

 ...

**Comment by LLehner** [comment]
Hi @ddzhang3, thank you for using squidpy. Apologies for the late response. 

You are right that ideally orientation should match, but for utilizing both image data and Anndata tables I would highly recommend you to make use of [spatialdata](https://spatialdata.scverse.org/en/latest/index.html). This is a data structure optimized for spatial omics data where you can store both tables, images and annotation of images. It also has functions for image alignment, which can solve orientation issues. Image container in squidpy will be deprecated in the future, instead we will work on compatibility with spatialdata. You can continue to use squidpy for analysis by using the anndata table from the spatialdata object.
