### ISSUE TITLE
Is squidpy.read.visium compatible with Visium HD data?

### ISSUE THREAD

**Issue by sunyumail93** [scverse/squidpy#843]
## Description
I got the following error when using squidpy.read.visium to read Visium HD Space Ranger output dir:
FileNotFoundError: [Errno 2] No such file or directory: /outs/binned_outputs/square_016um/spatial/tissue_positions_list.csv
I wondered if squidpy is compatible with Visium HD output?

## Minimal reproducible example
```
adata=sq.read.visium("/outs")
```

## Version
squidpy==1.5.0

**Comment by giovp** [comment]
hi @sunyumail93 indeed it is incompatible, for a visiumHD reader, https://spatialdata.scverse.org/projects/io/en/latest/generated/spatialdata_io.visium_hd.html#spatialdata_io.visium_hd

**Comment by ktpolanski** [comment]
Seeing how https://github.com/scverse/scanpy/pull/2992 mentions deprecation in favour of squidpy, it would probably make sense to just toss in parquet support?
