### ISSUE TITLE
Is Xenium data can be 3D visualization/ can the Stardist do 3D segmentation/ is squidy able to crop image for further analysis

### ISSUE THREAD

**Issue by Yifan-debug** [scverse/squidpy#873]
Hi developer, 

Thank so much for the package. I'm currently looking for a package can do 3D segmentation and visualizarion on xenium dataset. And also can crop the dataset to the region I'm only interested to avoid the large requirement of power.

**Comment by Yifan-debug** [comment]
I see it could do 3D on merfish. I'm wondering it also could do in Xenium data

**Comment by giovp** [comment]
you might want to take a look at https://github.com/gustaveroussy/sopa closing this for the moment, feel free to reopen
