### ISSUE TITLE
is there a way to view older versions of the documentation over on readthedocs?

### ISSUE THREAD

**Issue by owenwilkins** [scverse/squidpy#888]
...

**Comment by giovp** [comment]
hi @owenwilkins , unfortunately not, but you can see the source code of previous versions with the branch toggle 
<img width="357" alt="image" src="https://github.com/user-attachments/assets/89764e68-ca0d-4483-9712-1aff1a8a5c55">

**Comment by owenwilkins** [comment]
Ok thanks for getting back.

From: Giovanni Palla ***@***.***>
Date: Tuesday, September 17, 2024 at 5:30 PM
To: scverse/squidpy ***@***.***>
Cc: Owen Michael Wilkins ***@***.***>, Mention ***@***.***>
Subject: Re: [scverse/squidpy] is there a way to view older versions of the documentation over on readthedocs? (Issue #888)

hi @owenwilkins<https://github.com/owenwilkins> , unfortunately not, but you can see the source code of previous versions with the branch toggle
image.png (view on web)<https://github.com/user-attachments/assets/89764e68-ca0d-4483-9712-1aff1a8a5c55>

**Comment by giovp** [comment]
closing for now, feel free to reopen
