### ISSUE TITLE
Tutorial for Visium applicable to Visium HD?

### ISSUE THREAD

**Issue by spatts14** [scverse/squidpy#893]
Hi all,

Thanks so much for your work! 

I wanted to enquire if the tutorial for visium will still be suitable for visium HD data? Im curious as now the spot sizes are smaller and there is a grid-like system rather than the gaps between previous spots.

Thanks!
...

**Comment by LLehner** [comment]
Hi @spatts14,

regarding the grid-like system some things will probably need to be adjusted. But all the tutorials will soon get a rework and also incorporate spatialdata, then there will also be a Visium HD tutorial!

**Comment by LLehner** [comment]
@spatts14 In the meantime i would suggest using the Visium HD reader from spatialdata-io (see API [here](https://spatialdata.scverse.org/projects/io/en/latest/generated/spatialdata_io.visium_hd.html)) and check out the spatialdata Visium HD tutorial [here](https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/technology_visium_hd.html). You can continue working with squidpy, using the spatialdata object.

**Comment by spatts14** [comment]
Thanks @LLehner so much! I will check them out. Looking forward to the new tutorials.
