### ISSUE TITLE
How to save the iamge as svs or png?

### ISSUE THREAD

**Issue by HelloWorldLTY** [scverse/squidpy#895]
Hi, I am interested in reading the image from img object using PIL. Would you please share some steps I need to finish this part? I found tha the np.array has larger value than 255, and thus the data cannot be directly applied.

**Comment by LLehner** [comment]
Hi @HelloWorldLTY, do you mean svs or svg? If svg (and png) then you should be able to do

`img.save("name.png", "PNG")`

If the reason why this doesn't work is related to squidpy, please provide a code snippet.
