### ISSUE TITLE
New xarray release (v2024.10.0) is breaking squidpy install

### ISSUE THREAD

**Issue by ajulienla** [scverse/squidpy#907]
I tried to install a brand new `squidpy` environemnt and the latest release of `xarray`  is not working with the current implementation of `squidpy`  (through `datatree`) 

It seems the latest release broke functionalities eventhough I don't see it described in the release's log.

Below is a minimal example using `uv` but poetry/conda/pip would be the same.

````
uv init
uv add squidpy
uv run python -c "import squidpy"


 File "**/.venv/lib/python3.11/site-packages/datatree/datatree.py", line 33, in <module>
    from xarray.core.utils import (
ImportError: cannot import name 'HybridMappingProxy' from 'xarray.core.utils' (**/.venv/lib/python3.11/site-packages/xarray/core/utils.py)
````

**Lowering & pinning**  `xarray` version works.

With the same install:

````
uv add "xarray<v2024.10.0"
uv run python -c "import squidpy"
````

This would be useful for now as a workaround  for now in the toml to avoid new installation to fails.

Thanks !

**Comment by Roger-GOAT** [comment]
same issue. How to fix it??

**Comment by ilan-gold** [comment]
Fixed in 1.6.2 by upper bounding xarray for now

**Comment by christophechu** [comment]
Yes, it is very important to  relax the xarray upper bound~

**Comment by ilan-gold** [comment]
@marcovarrone The build should probably be excluded, not upper bounded.  Furthermore, I think the issue was in `datatree` anyway so that is probably the package that receives the bound/exclusion but at the time, I needed to fix it so applied something quickly.  If you want to make a PR, that would be great.
