### ISSUE TITLE
import squidpy and get an error

### ISSUE THREAD

**Issue by xyuechen** [scverse/squidpy#915]
...when I test my code in colab and install squidpy==1.6.1 and anndata==0.9.2,I get an error "ImportError: cannot import name 'SparseCSCView' from 'anndata._core.views' (/usr/local/lib/python3.10/dist-packages/anndata/_core/views.py)"

I thought it might be the version contradiction in squidpy and anndata. But I found that squidpy==1.6.1 can't compatible with anndata>=0.11.0. So I might not get the error.

And then I try to "from anndata._core.views import SparseCSCView",but it remind that anndata only have "SparseCSCArrayView" and "SparseCSCMatrixView"

I need some help.thanks for everyone which can answer me.

**Comment by ilan-gold** [comment]
Fixed in squidpy 1.6.2
